// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: dashboards/v1/dashboards.proto

package dashboards

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_dashboards_v1_dashboards_proto_rawDescGZIP(), []int{0}
}

func (x *GetAllRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetAllResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Dashboards    []*GetAllResponse_Dashboard `protobuf:"bytes,1,rep,name=dashboards,proto3" json:"dashboards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllResponse) Reset() {
	*x = GetAllResponse{}
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResponse) ProtoMessage() {}

func (x *GetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResponse.ProtoReflect.Descriptor instead.
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return file_dashboards_v1_dashboards_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllResponse) GetDashboards() []*GetAllResponse_Dashboard {
	if x != nil {
		return x.Dashboards
	}
	return nil
}

type GetMyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyRequest) Reset() {
	*x = GetMyRequest{}
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyRequest) ProtoMessage() {}

func (x *GetMyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyRequest.ProtoReflect.Descriptor instead.
func (*GetMyRequest) Descriptor() ([]byte, []int) {
	return file_dashboards_v1_dashboards_proto_rawDescGZIP(), []int{2}
}

func (x *GetMyRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetMyRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetMyResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Dashboards    []*GetMyResponse_Dashboard `protobuf:"bytes,1,rep,name=dashboards,proto3" json:"dashboards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyResponse) Reset() {
	*x = GetMyResponse{}
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyResponse) ProtoMessage() {}

func (x *GetMyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyResponse.ProtoReflect.Descriptor instead.
func (*GetMyResponse) Descriptor() ([]byte, []int) {
	return file_dashboards_v1_dashboards_proto_rawDescGZIP(), []int{3}
}

func (x *GetMyResponse) GetDashboards() []*GetMyResponse_Dashboard {
	if x != nil {
		return x.Dashboards
	}
	return nil
}

type GetByUUIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByUUIDRequest) Reset() {
	*x = GetByUUIDRequest{}
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByUUIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByUUIDRequest) ProtoMessage() {}

func (x *GetByUUIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByUUIDRequest.ProtoReflect.Descriptor instead.
func (*GetByUUIDRequest) Descriptor() ([]byte, []int) {
	return file_dashboards_v1_dashboards_proto_rawDescGZIP(), []int{4}
}

func (x *GetByUUIDRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetByUUIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Meta          string                 `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	OwnerName     string                 `protobuf:"bytes,3,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByUUIDResponse) Reset() {
	*x = GetByUUIDResponse{}
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByUUIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByUUIDResponse) ProtoMessage() {}

func (x *GetByUUIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByUUIDResponse.ProtoReflect.Descriptor instead.
func (*GetByUUIDResponse) Descriptor() ([]byte, []int) {
	return file_dashboards_v1_dashboards_proto_rawDescGZIP(), []int{5}
}

func (x *GetByUUIDResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetByUUIDResponse) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

func (x *GetByUUIDResponse) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Meta          string                 `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_dashboards_v1_dashboards_proto_rawDescGZIP(), []int{6}
}

func (x *CreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRequest) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_dashboards_v1_dashboards_proto_rawDescGZIP(), []int{7}
}

func (x *CreateResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Meta          *string                `protobuf:"bytes,3,opt,name=meta,proto3,oneof" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_dashboards_v1_dashboards_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UpdateRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateRequest) GetMeta() string {
	if x != nil && x.Meta != nil {
		return *x.Meta
	}
	return ""
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_dashboards_v1_dashboards_proto_rawDescGZIP(), []int{9}
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_dashboards_v1_dashboards_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_dashboards_v1_dashboards_proto_rawDescGZIP(), []int{11}
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Filter        *SearchRequest_Filter  `protobuf:"bytes,4,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_dashboards_v1_dashboards_proto_rawDescGZIP(), []int{12}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SearchRequest) GetFilter() *SearchRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type SearchResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Dashboards    []*SearchResponse_Dashboard `protobuf:"bytes,1,rep,name=dashboards,proto3" json:"dashboards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_dashboards_v1_dashboards_proto_rawDescGZIP(), []int{13}
}

func (x *SearchResponse) GetDashboards() []*SearchResponse_Dashboard {
	if x != nil {
		return x.Dashboards
	}
	return nil
}

type GetAllResponse_Dashboard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OwnerName     string                 `protobuf:"bytes,3,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllResponse_Dashboard) Reset() {
	*x = GetAllResponse_Dashboard{}
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllResponse_Dashboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResponse_Dashboard) ProtoMessage() {}

func (x *GetAllResponse_Dashboard) ProtoReflect() protoreflect.Message {
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResponse_Dashboard.ProtoReflect.Descriptor instead.
func (*GetAllResponse_Dashboard) Descriptor() ([]byte, []int) {
	return file_dashboards_v1_dashboards_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetAllResponse_Dashboard) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetAllResponse_Dashboard) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetAllResponse_Dashboard) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

type GetMyResponse_Dashboard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyResponse_Dashboard) Reset() {
	*x = GetMyResponse_Dashboard{}
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyResponse_Dashboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyResponse_Dashboard) ProtoMessage() {}

func (x *GetMyResponse_Dashboard) ProtoReflect() protoreflect.Message {
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyResponse_Dashboard.ProtoReflect.Descriptor instead.
func (*GetMyResponse_Dashboard) Descriptor() ([]byte, []int) {
	return file_dashboards_v1_dashboards_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetMyResponse_Dashboard) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetMyResponse_Dashboard) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SearchRequest_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerName     *string                `protobuf:"bytes,1,opt,name=owner_name,json=ownerName,proto3,oneof" json:"owner_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest_Filter) Reset() {
	*x = SearchRequest_Filter{}
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest_Filter) ProtoMessage() {}

func (x *SearchRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest_Filter.ProtoReflect.Descriptor instead.
func (*SearchRequest_Filter) Descriptor() ([]byte, []int) {
	return file_dashboards_v1_dashboards_proto_rawDescGZIP(), []int{12, 0}
}

func (x *SearchRequest_Filter) GetOwnerName() string {
	if x != nil && x.OwnerName != nil {
		return *x.OwnerName
	}
	return ""
}

type SearchResponse_Dashboard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OwnerName     string                 `protobuf:"bytes,3,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse_Dashboard) Reset() {
	*x = SearchResponse_Dashboard{}
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse_Dashboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse_Dashboard) ProtoMessage() {}

func (x *SearchResponse_Dashboard) ProtoReflect() protoreflect.Message {
	mi := &file_dashboards_v1_dashboards_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse_Dashboard.ProtoReflect.Descriptor instead.
func (*SearchResponse_Dashboard) Descriptor() ([]byte, []int) {
	return file_dashboards_v1_dashboards_proto_rawDescGZIP(), []int{13, 0}
}

func (x *SearchResponse_Dashboard) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *SearchResponse_Dashboard) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchResponse_Dashboard) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

var File_dashboards_v1_dashboards_proto protoreflect.FileDescriptor

const file_dashboards_v1_dashboards_proto_rawDesc = "" +
	"\n" +
	"\x1edashboards/v1/dashboards.proto\x12\rdashboards.v1\"=\n" +
	"\rGetAllRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"\xad\x01\n" +
	"\x0eGetAllResponse\x12G\n" +
	"\n" +
	"dashboards\x18\x01 \x03(\v2'.dashboards.v1.GetAllResponse.DashboardR\n" +
	"dashboards\x1aR\n" +
	"\tDashboard\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x03 \x01(\tR\townerName\"<\n" +
	"\fGetMyRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"\x8c\x01\n" +
	"\rGetMyResponse\x12F\n" +
	"\n" +
	"dashboards\x18\x01 \x03(\v2&.dashboards.v1.GetMyResponse.DashboardR\n" +
	"dashboards\x1a3\n" +
	"\tDashboard\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"&\n" +
	"\x10GetByUUIDRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"Z\n" +
	"\x11GetByUUIDResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04meta\x18\x02 \x01(\tR\x04meta\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x03 \x01(\tR\townerName\"7\n" +
	"\rCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04meta\x18\x02 \x01(\tR\x04meta\"$\n" +
	"\x0eCreateResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"g\n" +
	"\rUpdateRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x17\n" +
	"\x04meta\x18\x03 \x01(\tH\x01R\x04meta\x88\x01\x01B\a\n" +
	"\x05_nameB\a\n" +
	"\x05_meta\"\x10\n" +
	"\x0eUpdateResponse\"#\n" +
	"\rDeleteRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\x10\n" +
	"\x0eDeleteResponse\"\xdd\x01\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12@\n" +
	"\x06filter\x18\x04 \x01(\v2#.dashboards.v1.SearchRequest.FilterH\x00R\x06filter\x88\x01\x01\x1a;\n" +
	"\x06Filter\x12\"\n" +
	"\n" +
	"owner_name\x18\x01 \x01(\tH\x00R\townerName\x88\x01\x01B\r\n" +
	"\v_owner_nameB\t\n" +
	"\a_filter\"\xad\x01\n" +
	"\x0eSearchResponse\x12G\n" +
	"\n" +
	"dashboards\x18\x01 \x03(\v2'.dashboards.v1.SearchResponse.DashboardR\n" +
	"dashboards\x1aR\n" +
	"\tDashboard\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x03 \x01(\tR\townerName2\x98\x04\n" +
	"\x11DashboardsService\x12G\n" +
	"\x06GetAll\x12\x1c.dashboards.v1.GetAllRequest\x1a\x1d.dashboards.v1.GetAllResponse\"\x00\x12D\n" +
	"\x05GetMy\x12\x1b.dashboards.v1.GetMyRequest\x1a\x1c.dashboards.v1.GetMyResponse\"\x00\x12P\n" +
	"\tGetByUUID\x12\x1f.dashboards.v1.GetByUUIDRequest\x1a .dashboards.v1.GetByUUIDResponse\"\x00\x12G\n" +
	"\x06Create\x12\x1c.dashboards.v1.CreateRequest\x1a\x1d.dashboards.v1.CreateResponse\"\x00\x12G\n" +
	"\x06Update\x12\x1c.dashboards.v1.UpdateRequest\x1a\x1d.dashboards.v1.UpdateResponse\"\x00\x12G\n" +
	"\x06Delete\x12\x1c.dashboards.v1.DeleteRequest\x1a\x1d.dashboards.v1.DeleteResponse\"\x00\x12G\n" +
	"\x06Search\x12\x1c.dashboards.v1.SearchRequest\x1a\x1d.dashboards.v1.SearchResponse\"\x00B9Z7github.com/ozontech/seq-ui/pkg/dashboards/v1;dashboardsb\x06proto3"

var (
	file_dashboards_v1_dashboards_proto_rawDescOnce sync.Once
	file_dashboards_v1_dashboards_proto_rawDescData []byte
)

func file_dashboards_v1_dashboards_proto_rawDescGZIP() []byte {
	file_dashboards_v1_dashboards_proto_rawDescOnce.Do(func() {
		file_dashboards_v1_dashboards_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dashboards_v1_dashboards_proto_rawDesc), len(file_dashboards_v1_dashboards_proto_rawDesc)))
	})
	return file_dashboards_v1_dashboards_proto_rawDescData
}

var file_dashboards_v1_dashboards_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_dashboards_v1_dashboards_proto_goTypes = []any{
	(*GetAllRequest)(nil),            // 0: dashboards.v1.GetAllRequest
	(*GetAllResponse)(nil),           // 1: dashboards.v1.GetAllResponse
	(*GetMyRequest)(nil),             // 2: dashboards.v1.GetMyRequest
	(*GetMyResponse)(nil),            // 3: dashboards.v1.GetMyResponse
	(*GetByUUIDRequest)(nil),         // 4: dashboards.v1.GetByUUIDRequest
	(*GetByUUIDResponse)(nil),        // 5: dashboards.v1.GetByUUIDResponse
	(*CreateRequest)(nil),            // 6: dashboards.v1.CreateRequest
	(*CreateResponse)(nil),           // 7: dashboards.v1.CreateResponse
	(*UpdateRequest)(nil),            // 8: dashboards.v1.UpdateRequest
	(*UpdateResponse)(nil),           // 9: dashboards.v1.UpdateResponse
	(*DeleteRequest)(nil),            // 10: dashboards.v1.DeleteRequest
	(*DeleteResponse)(nil),           // 11: dashboards.v1.DeleteResponse
	(*SearchRequest)(nil),            // 12: dashboards.v1.SearchRequest
	(*SearchResponse)(nil),           // 13: dashboards.v1.SearchResponse
	(*GetAllResponse_Dashboard)(nil), // 14: dashboards.v1.GetAllResponse.Dashboard
	(*GetMyResponse_Dashboard)(nil),  // 15: dashboards.v1.GetMyResponse.Dashboard
	(*SearchRequest_Filter)(nil),     // 16: dashboards.v1.SearchRequest.Filter
	(*SearchResponse_Dashboard)(nil), // 17: dashboards.v1.SearchResponse.Dashboard
}
var file_dashboards_v1_dashboards_proto_depIdxs = []int32{
	14, // 0: dashboards.v1.GetAllResponse.dashboards:type_name -> dashboards.v1.GetAllResponse.Dashboard
	15, // 1: dashboards.v1.GetMyResponse.dashboards:type_name -> dashboards.v1.GetMyResponse.Dashboard
	16, // 2: dashboards.v1.SearchRequest.filter:type_name -> dashboards.v1.SearchRequest.Filter
	17, // 3: dashboards.v1.SearchResponse.dashboards:type_name -> dashboards.v1.SearchResponse.Dashboard
	0,  // 4: dashboards.v1.DashboardsService.GetAll:input_type -> dashboards.v1.GetAllRequest
	2,  // 5: dashboards.v1.DashboardsService.GetMy:input_type -> dashboards.v1.GetMyRequest
	4,  // 6: dashboards.v1.DashboardsService.GetByUUID:input_type -> dashboards.v1.GetByUUIDRequest
	6,  // 7: dashboards.v1.DashboardsService.Create:input_type -> dashboards.v1.CreateRequest
	8,  // 8: dashboards.v1.DashboardsService.Update:input_type -> dashboards.v1.UpdateRequest
	10, // 9: dashboards.v1.DashboardsService.Delete:input_type -> dashboards.v1.DeleteRequest
	12, // 10: dashboards.v1.DashboardsService.Search:input_type -> dashboards.v1.SearchRequest
	1,  // 11: dashboards.v1.DashboardsService.GetAll:output_type -> dashboards.v1.GetAllResponse
	3,  // 12: dashboards.v1.DashboardsService.GetMy:output_type -> dashboards.v1.GetMyResponse
	5,  // 13: dashboards.v1.DashboardsService.GetByUUID:output_type -> dashboards.v1.GetByUUIDResponse
	7,  // 14: dashboards.v1.DashboardsService.Create:output_type -> dashboards.v1.CreateResponse
	9,  // 15: dashboards.v1.DashboardsService.Update:output_type -> dashboards.v1.UpdateResponse
	11, // 16: dashboards.v1.DashboardsService.Delete:output_type -> dashboards.v1.DeleteResponse
	13, // 17: dashboards.v1.DashboardsService.Search:output_type -> dashboards.v1.SearchResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_dashboards_v1_dashboards_proto_init() }
func file_dashboards_v1_dashboards_proto_init() {
	if File_dashboards_v1_dashboards_proto != nil {
		return
	}
	file_dashboards_v1_dashboards_proto_msgTypes[8].OneofWrappers = []any{}
	file_dashboards_v1_dashboards_proto_msgTypes[12].OneofWrappers = []any{}
	file_dashboards_v1_dashboards_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dashboards_v1_dashboards_proto_rawDesc), len(file_dashboards_v1_dashboards_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dashboards_v1_dashboards_proto_goTypes,
		DependencyIndexes: file_dashboards_v1_dashboards_proto_depIdxs,
		MessageInfos:      file_dashboards_v1_dashboards_proto_msgTypes,
	}.Build()
	File_dashboards_v1_dashboards_proto = out.File
	file_dashboards_v1_dashboards_proto_goTypes = nil
	file_dashboards_v1_dashboards_proto_depIdxs = nil
}
