version: "2"
linters:
  default: none
  enable:
    - errcheck
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - whitespace
    - unparam
    - unused
  settings:
    goconst:
      min-len: 2
      min-occurrences: 3
    misspell:
      locale: US
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - whyNoLint
        - paramTypeCombine
        - unnamedResult
        - sprintfQuotedString
        - tooManyResultsChecker
        - hugeParam
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
          - goconst
      - linters: [ govet ]
        text: 'declaration of "(err|ctx)"'
      - linters: [ gosec ]
        text: 'integer overflow conversion'
      - linters: [ staticcheck ]
        text: 'SA1019:' # <something> is deprecated 
      - linters: [ staticcheck ]
        text: 'QF1008:' # could remove embedded field <something> from selector 
    paths:
      - bin
      - vendor
      - var
      - tmp
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    paths:
      - bin
      - vendor
      - var
      - tmp
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0