before:
  hooks:
    - go mod download
env:
  - CGO_ENABLED=0
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
release:
  prerelease: auto

builds:
  - main: ./cmd/seq-ui
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -X github.com/ozontech/seq-ui/buildinfo.Version={{.Version}}