version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  redis:
    image: redis:latest
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    restart: always
    ports:
      - "${CLICKHOUSE_HTTP_PORT}:8123"
      - "${CLICKHOUSE_TCP_PORT}:9000"
    environment:
      CLICKHOUSE_DB: "seq_ui_server"
      CLICKHOUSE_USER: "default"
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
