// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: errorgroups/v1/errorgroups.proto

package errorgroups

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order int32

const (
	Order_ORDER_FREQUENT Order = 0
	Order_ORDER_LATEST   Order = 1
	Order_ORDER_OLDEST   Order = 2
)

// Enum value maps for Order.
var (
	Order_name = map[int32]string{
		0: "ORDER_FREQUENT",
		1: "ORDER_LATEST",
		2: "ORDER_OLDEST",
	}
	Order_value = map[string]int32{
		"ORDER_FREQUENT": 0,
		"ORDER_LATEST":   1,
		"ORDER_OLDEST":   2,
	}
)

func (x Order) Enum() *Order {
	p := new(Order)
	*p = x
	return p
}

func (x Order) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Order) Descriptor() protoreflect.EnumDescriptor {
	return file_errorgroups_v1_errorgroups_proto_enumTypes[0].Descriptor()
}

func (Order) Type() protoreflect.EnumType {
	return &file_errorgroups_v1_errorgroups_proto_enumTypes[0]
}

func (x Order) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Order.Descriptor instead.
func (Order) EnumDescriptor() ([]byte, []int) {
	return file_errorgroups_v1_errorgroups_proto_rawDescGZIP(), []int{0}
}

type TimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Duration      *durationpb.Duration   `protobuf:"bytes,1,opt,name=duration,proto3" json:"duration,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_errorgroups_v1_errorgroups_proto_rawDescGZIP(), []int{0}
}

func (x *TimeRange) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *TimeRange) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *TimeRange) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

type GetGroupsRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Service string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Env     *string                `protobuf:"bytes,2,opt,name=env,proto3,oneof" json:"env,omitempty"`
	Release *string                `protobuf:"bytes,3,opt,name=release,proto3,oneof" json:"release,omitempty"`
	// Deprecated: Marked as deprecated in errorgroups/v1/errorgroups.proto.
	Duration      *durationpb.Duration     `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Limit         uint32                   `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                   `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	Order         Order                    `protobuf:"varint,7,opt,name=order,proto3,enum=errorgroups.v1.Order" json:"order,omitempty"`
	WithTotal     bool                     `protobuf:"varint,8,opt,name=with_total,json=withTotal,proto3" json:"with_total,omitempty"`
	Source        *string                  `protobuf:"bytes,9,opt,name=source,proto3,oneof" json:"source,omitempty"`
	Filter        *GetGroupsRequest_Filter `protobuf:"bytes,10,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	TimeRange     *TimeRange               `protobuf:"bytes,11,opt,name=time_range,json=timeRange,proto3,oneof" json:"time_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupsRequest) Reset() {
	*x = GetGroupsRequest{}
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsRequest) ProtoMessage() {}

func (x *GetGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsRequest.ProtoReflect.Descriptor instead.
func (*GetGroupsRequest) Descriptor() ([]byte, []int) {
	return file_errorgroups_v1_errorgroups_proto_rawDescGZIP(), []int{1}
}

func (x *GetGroupsRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GetGroupsRequest) GetEnv() string {
	if x != nil && x.Env != nil {
		return *x.Env
	}
	return ""
}

func (x *GetGroupsRequest) GetRelease() string {
	if x != nil && x.Release != nil {
		return *x.Release
	}
	return ""
}

// Deprecated: Marked as deprecated in errorgroups/v1/errorgroups.proto.
func (x *GetGroupsRequest) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *GetGroupsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetGroupsRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetGroupsRequest) GetOrder() Order {
	if x != nil {
		return x.Order
	}
	return Order_ORDER_FREQUENT
}

func (x *GetGroupsRequest) GetWithTotal() bool {
	if x != nil {
		return x.WithTotal
	}
	return false
}

func (x *GetGroupsRequest) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *GetGroupsRequest) GetFilter() *GetGroupsRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *GetGroupsRequest) GetTimeRange() *TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

type GetGroupsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Total         uint64                     `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Groups        []*GetGroupsResponse_Group `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupsResponse) Reset() {
	*x = GetGroupsResponse{}
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsResponse) ProtoMessage() {}

func (x *GetGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsResponse.ProtoReflect.Descriptor instead.
func (*GetGroupsResponse) Descriptor() ([]byte, []int) {
	return file_errorgroups_v1_errorgroups_proto_rawDescGZIP(), []int{2}
}

func (x *GetGroupsResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetGroupsResponse) GetGroups() []*GetGroupsResponse_Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type GetTopGroupsRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Env    *string                `protobuf:"bytes,1,opt,name=env,proto3,oneof" json:"env,omitempty"`
	Source *string                `protobuf:"bytes,2,opt,name=source,proto3,oneof" json:"source,omitempty"`
	// Deprecated: Marked as deprecated in errorgroups/v1/errorgroups.proto.
	Duration      *durationpb.Duration `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Limit         uint32               `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32               `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	WithTotal     bool                 `protobuf:"varint,6,opt,name=with_total,json=withTotal,proto3" json:"with_total,omitempty"`
	TimeRange     *TimeRange           `protobuf:"bytes,7,opt,name=time_range,json=timeRange,proto3,oneof" json:"time_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopGroupsRequest) Reset() {
	*x = GetTopGroupsRequest{}
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopGroupsRequest) ProtoMessage() {}

func (x *GetTopGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopGroupsRequest.ProtoReflect.Descriptor instead.
func (*GetTopGroupsRequest) Descriptor() ([]byte, []int) {
	return file_errorgroups_v1_errorgroups_proto_rawDescGZIP(), []int{3}
}

func (x *GetTopGroupsRequest) GetEnv() string {
	if x != nil && x.Env != nil {
		return *x.Env
	}
	return ""
}

func (x *GetTopGroupsRequest) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

// Deprecated: Marked as deprecated in errorgroups/v1/errorgroups.proto.
func (x *GetTopGroupsRequest) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *GetTopGroupsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTopGroupsRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetTopGroupsRequest) GetWithTotal() bool {
	if x != nil {
		return x.WithTotal
	}
	return false
}

func (x *GetTopGroupsRequest) GetTimeRange() *TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

type GetTopGroupsResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Total         uint64                        `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Groups        []*GetTopGroupsResponse_Group `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopGroupsResponse) Reset() {
	*x = GetTopGroupsResponse{}
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopGroupsResponse) ProtoMessage() {}

func (x *GetTopGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopGroupsResponse.ProtoReflect.Descriptor instead.
func (*GetTopGroupsResponse) Descriptor() ([]byte, []int) {
	return file_errorgroups_v1_errorgroups_proto_rawDescGZIP(), []int{4}
}

func (x *GetTopGroupsResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetTopGroupsResponse) GetGroups() []*GetTopGroupsResponse_Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type GetHistRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Service   *string                `protobuf:"bytes,1,opt,name=service,proto3,oneof" json:"service,omitempty"`
	GroupHash *uint64                `protobuf:"varint,2,opt,name=group_hash,json=groupHash,proto3,oneof" json:"group_hash,omitempty"`
	Env       *string                `protobuf:"bytes,3,opt,name=env,proto3,oneof" json:"env,omitempty"`
	Release   *string                `protobuf:"bytes,4,opt,name=release,proto3,oneof" json:"release,omitempty"`
	// Deprecated: Marked as deprecated in errorgroups/v1/errorgroups.proto.
	Duration      *durationpb.Duration   `protobuf:"bytes,5,opt,name=duration,proto3,oneof" json:"duration,omitempty"`
	Source        *string                `protobuf:"bytes,6,opt,name=source,proto3,oneof" json:"source,omitempty"`
	TimeRange     *TimeRange             `protobuf:"bytes,7,opt,name=time_range,json=timeRange,proto3,oneof" json:"time_range,omitempty"`
	Filter        *GetHistRequest_Filter `protobuf:"bytes,8,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistRequest) Reset() {
	*x = GetHistRequest{}
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistRequest) ProtoMessage() {}

func (x *GetHistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistRequest.ProtoReflect.Descriptor instead.
func (*GetHistRequest) Descriptor() ([]byte, []int) {
	return file_errorgroups_v1_errorgroups_proto_rawDescGZIP(), []int{5}
}

func (x *GetHistRequest) GetService() string {
	if x != nil && x.Service != nil {
		return *x.Service
	}
	return ""
}

func (x *GetHistRequest) GetGroupHash() uint64 {
	if x != nil && x.GroupHash != nil {
		return *x.GroupHash
	}
	return 0
}

func (x *GetHistRequest) GetEnv() string {
	if x != nil && x.Env != nil {
		return *x.Env
	}
	return ""
}

func (x *GetHistRequest) GetRelease() string {
	if x != nil && x.Release != nil {
		return *x.Release
	}
	return ""
}

// Deprecated: Marked as deprecated in errorgroups/v1/errorgroups.proto.
func (x *GetHistRequest) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *GetHistRequest) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *GetHistRequest) GetTimeRange() *TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *GetHistRequest) GetFilter() *GetHistRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type GetHistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buckets       []*Bucket              `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
	Interval      uint64                 `protobuf:"varint,2,opt,name=interval,proto3" json:"interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistResponse) Reset() {
	*x = GetHistResponse{}
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistResponse) ProtoMessage() {}

func (x *GetHistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistResponse.ProtoReflect.Descriptor instead.
func (*GetHistResponse) Descriptor() ([]byte, []int) {
	return file_errorgroups_v1_errorgroups_proto_rawDescGZIP(), []int{6}
}

func (x *GetHistResponse) GetBuckets() []*Bucket {
	if x != nil {
		return x.Buckets
	}
	return nil
}

func (x *GetHistResponse) GetInterval() uint64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

type Bucket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Count         uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bucket) Reset() {
	*x = Bucket{}
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bucket) ProtoMessage() {}

func (x *Bucket) ProtoReflect() protoreflect.Message {
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bucket.ProtoReflect.Descriptor instead.
func (*Bucket) Descriptor() ([]byte, []int) {
	return file_errorgroups_v1_errorgroups_proto_rawDescGZIP(), []int{7}
}

func (x *Bucket) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Bucket) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetDetailsRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Service       *string                   `protobuf:"bytes,1,opt,name=service,proto3,oneof" json:"service,omitempty"`
	GroupHash     uint64                    `protobuf:"varint,2,opt,name=group_hash,json=groupHash,proto3" json:"group_hash,omitempty"`
	Env           *string                   `protobuf:"bytes,3,opt,name=env,proto3,oneof" json:"env,omitempty"`
	Release       *string                   `protobuf:"bytes,4,opt,name=release,proto3,oneof" json:"release,omitempty"`
	Source        *string                   `protobuf:"bytes,5,opt,name=source,proto3,oneof" json:"source,omitempty"`
	Filter        *GetDetailsRequest_Filter `protobuf:"bytes,6,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDetailsRequest) Reset() {
	*x = GetDetailsRequest{}
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetailsRequest) ProtoMessage() {}

func (x *GetDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetDetailsRequest) Descriptor() ([]byte, []int) {
	return file_errorgroups_v1_errorgroups_proto_rawDescGZIP(), []int{8}
}

func (x *GetDetailsRequest) GetService() string {
	if x != nil && x.Service != nil {
		return *x.Service
	}
	return ""
}

func (x *GetDetailsRequest) GetGroupHash() uint64 {
	if x != nil {
		return x.GroupHash
	}
	return 0
}

func (x *GetDetailsRequest) GetEnv() string {
	if x != nil && x.Env != nil {
		return *x.Env
	}
	return ""
}

func (x *GetDetailsRequest) GetRelease() string {
	if x != nil && x.Release != nil {
		return *x.Release
	}
	return ""
}

func (x *GetDetailsRequest) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *GetDetailsRequest) GetFilter() *GetDetailsRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type GetDetailsResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	GroupHash     uint64                            `protobuf:"varint,1,opt,name=group_hash,json=groupHash,proto3" json:"group_hash,omitempty"`
	Message       string                            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SeenTotal     uint64                            `protobuf:"varint,3,opt,name=seen_total,json=seenTotal,proto3" json:"seen_total,omitempty"`
	FirstSeenAt   *timestamppb.Timestamp            `protobuf:"bytes,4,opt,name=first_seen_at,json=firstSeenAt,proto3" json:"first_seen_at,omitempty"`
	LastSeenAt    *timestamppb.Timestamp            `protobuf:"bytes,5,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	Distributions *GetDetailsResponse_Distributions `protobuf:"bytes,6,opt,name=distributions,proto3" json:"distributions,omitempty"`
	LogTags       map[string]string                 `protobuf:"bytes,7,rep,name=log_tags,json=logTags,proto3" json:"log_tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Source        string                            `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDetailsResponse) Reset() {
	*x = GetDetailsResponse{}
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetailsResponse) ProtoMessage() {}

func (x *GetDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetDetailsResponse) Descriptor() ([]byte, []int) {
	return file_errorgroups_v1_errorgroups_proto_rawDescGZIP(), []int{9}
}

func (x *GetDetailsResponse) GetGroupHash() uint64 {
	if x != nil {
		return x.GroupHash
	}
	return 0
}

func (x *GetDetailsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetDetailsResponse) GetSeenTotal() uint64 {
	if x != nil {
		return x.SeenTotal
	}
	return 0
}

func (x *GetDetailsResponse) GetFirstSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeenAt
	}
	return nil
}

func (x *GetDetailsResponse) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

func (x *GetDetailsResponse) GetDistributions() *GetDetailsResponse_Distributions {
	if x != nil {
		return x.Distributions
	}
	return nil
}

func (x *GetDetailsResponse) GetLogTags() map[string]string {
	if x != nil {
		return x.LogTags
	}
	return nil
}

func (x *GetDetailsResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type GetReleasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Env           *string                `protobuf:"bytes,3,opt,name=env,proto3,oneof" json:"env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReleasesRequest) Reset() {
	*x = GetReleasesRequest{}
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReleasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReleasesRequest) ProtoMessage() {}

func (x *GetReleasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReleasesRequest.ProtoReflect.Descriptor instead.
func (*GetReleasesRequest) Descriptor() ([]byte, []int) {
	return file_errorgroups_v1_errorgroups_proto_rawDescGZIP(), []int{10}
}

func (x *GetReleasesRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GetReleasesRequest) GetEnv() string {
	if x != nil && x.Env != nil {
		return *x.Env
	}
	return ""
}

type GetReleasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Releases      []string               `protobuf:"bytes,1,rep,name=releases,proto3" json:"releases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReleasesResponse) Reset() {
	*x = GetReleasesResponse{}
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReleasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReleasesResponse) ProtoMessage() {}

func (x *GetReleasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReleasesResponse.ProtoReflect.Descriptor instead.
func (*GetReleasesResponse) Descriptor() ([]byte, []int) {
	return file_errorgroups_v1_errorgroups_proto_rawDescGZIP(), []int{11}
}

func (x *GetReleasesResponse) GetReleases() []string {
	if x != nil {
		return x.Releases
	}
	return nil
}

type GetServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Env           *string                `protobuf:"bytes,2,opt,name=env,proto3,oneof" json:"env,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServicesRequest) Reset() {
	*x = GetServicesRequest{}
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServicesRequest) ProtoMessage() {}

func (x *GetServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServicesRequest.ProtoReflect.Descriptor instead.
func (*GetServicesRequest) Descriptor() ([]byte, []int) {
	return file_errorgroups_v1_errorgroups_proto_rawDescGZIP(), []int{12}
}

func (x *GetServicesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *GetServicesRequest) GetEnv() string {
	if x != nil && x.Env != nil {
		return *x.Env
	}
	return ""
}

func (x *GetServicesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetServicesRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []string               `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServicesResponse) Reset() {
	*x = GetServicesResponse{}
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServicesResponse) ProtoMessage() {}

func (x *GetServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServicesResponse.ProtoReflect.Descriptor instead.
func (*GetServicesResponse) Descriptor() ([]byte, []int) {
	return file_errorgroups_v1_errorgroups_proto_rawDescGZIP(), []int{13}
}

func (x *GetServicesResponse) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

type DiffByReleasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Releases      []string               `protobuf:"bytes,2,rep,name=releases,proto3" json:"releases,omitempty"`
	Env           *string                `protobuf:"bytes,3,opt,name=env,proto3,oneof" json:"env,omitempty"`
	Source        *string                `protobuf:"bytes,4,opt,name=source,proto3,oneof" json:"source,omitempty"`
	Limit         uint32                 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	Order         Order                  `protobuf:"varint,7,opt,name=order,proto3,enum=errorgroups.v1.Order" json:"order,omitempty"`
	WithTotal     bool                   `protobuf:"varint,8,opt,name=with_total,json=withTotal,proto3" json:"with_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffByReleasesRequest) Reset() {
	*x = DiffByReleasesRequest{}
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffByReleasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffByReleasesRequest) ProtoMessage() {}

func (x *DiffByReleasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffByReleasesRequest.ProtoReflect.Descriptor instead.
func (*DiffByReleasesRequest) Descriptor() ([]byte, []int) {
	return file_errorgroups_v1_errorgroups_proto_rawDescGZIP(), []int{14}
}

func (x *DiffByReleasesRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *DiffByReleasesRequest) GetReleases() []string {
	if x != nil {
		return x.Releases
	}
	return nil
}

func (x *DiffByReleasesRequest) GetEnv() string {
	if x != nil && x.Env != nil {
		return *x.Env
	}
	return ""
}

func (x *DiffByReleasesRequest) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *DiffByReleasesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *DiffByReleasesRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *DiffByReleasesRequest) GetOrder() Order {
	if x != nil {
		return x.Order
	}
	return Order_ORDER_FREQUENT
}

func (x *DiffByReleasesRequest) GetWithTotal() bool {
	if x != nil {
		return x.WithTotal
	}
	return false
}

type DiffByReleasesResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Total         uint64                          `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Groups        []*DiffByReleasesResponse_Group `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffByReleasesResponse) Reset() {
	*x = DiffByReleasesResponse{}
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffByReleasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffByReleasesResponse) ProtoMessage() {}

func (x *DiffByReleasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffByReleasesResponse.ProtoReflect.Descriptor instead.
func (*DiffByReleasesResponse) Descriptor() ([]byte, []int) {
	return file_errorgroups_v1_errorgroups_proto_rawDescGZIP(), []int{15}
}

func (x *DiffByReleasesResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DiffByReleasesResponse) GetGroups() []*DiffByReleasesResponse_Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type GetServiceFiltersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Env           *string                `protobuf:"bytes,2,opt,name=env,proto3,oneof" json:"env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceFiltersRequest) Reset() {
	*x = GetServiceFiltersRequest{}
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceFiltersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceFiltersRequest) ProtoMessage() {}

func (x *GetServiceFiltersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceFiltersRequest.ProtoReflect.Descriptor instead.
func (*GetServiceFiltersRequest) Descriptor() ([]byte, []int) {
	return file_errorgroups_v1_errorgroups_proto_rawDescGZIP(), []int{16}
}

func (x *GetServiceFiltersRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GetServiceFiltersRequest) GetEnv() string {
	if x != nil && x.Env != nil {
		return *x.Env
	}
	return ""
}

type GetServiceFiltersResponse struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Filters       []*GetServiceFiltersResponse_Filter `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceFiltersResponse) Reset() {
	*x = GetServiceFiltersResponse{}
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceFiltersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceFiltersResponse) ProtoMessage() {}

func (x *GetServiceFiltersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceFiltersResponse.ProtoReflect.Descriptor instead.
func (*GetServiceFiltersResponse) Descriptor() ([]byte, []int) {
	return file_errorgroups_v1_errorgroups_proto_rawDescGZIP(), []int{17}
}

func (x *GetServiceFiltersResponse) GetFilters() []*GetServiceFiltersResponse_Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type GetGroupsRequest_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsNew         bool                   `protobuf:"varint,1,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`
	Custom        map[string]string      `protobuf:"bytes,2,rep,name=custom,proto3" json:"custom,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupsRequest_Filter) Reset() {
	*x = GetGroupsRequest_Filter{}
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupsRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsRequest_Filter) ProtoMessage() {}

func (x *GetGroupsRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsRequest_Filter.ProtoReflect.Descriptor instead.
func (*GetGroupsRequest_Filter) Descriptor() ([]byte, []int) {
	return file_errorgroups_v1_errorgroups_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetGroupsRequest_Filter) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *GetGroupsRequest_Filter) GetCustom() map[string]string {
	if x != nil {
		return x.Custom
	}
	return nil
}

type GetGroupsResponse_Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          uint64                 `protobuf:"varint,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SeenTotal     uint64                 `protobuf:"varint,3,opt,name=seen_total,json=seenTotal,proto3" json:"seen_total,omitempty"`
	FirstSeenAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=first_seen_at,json=firstSeenAt,proto3" json:"first_seen_at,omitempty"`
	LastSeenAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	Source        string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupsResponse_Group) Reset() {
	*x = GetGroupsResponse_Group{}
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupsResponse_Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsResponse_Group) ProtoMessage() {}

func (x *GetGroupsResponse_Group) ProtoReflect() protoreflect.Message {
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsResponse_Group.ProtoReflect.Descriptor instead.
func (*GetGroupsResponse_Group) Descriptor() ([]byte, []int) {
	return file_errorgroups_v1_errorgroups_proto_rawDescGZIP(), []int{2, 0}
}

func (x *GetGroupsResponse_Group) GetHash() uint64 {
	if x != nil {
		return x.Hash
	}
	return 0
}

func (x *GetGroupsResponse_Group) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetGroupsResponse_Group) GetSeenTotal() uint64 {
	if x != nil {
		return x.SeenTotal
	}
	return 0
}

func (x *GetGroupsResponse_Group) GetFirstSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeenAt
	}
	return nil
}

func (x *GetGroupsResponse_Group) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

func (x *GetGroupsResponse_Group) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type GetTopGroupsResponse_Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          uint64                 `protobuf:"varint,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	SeenTotal     uint64                 `protobuf:"varint,4,opt,name=seen_total,json=seenTotal,proto3" json:"seen_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopGroupsResponse_Group) Reset() {
	*x = GetTopGroupsResponse_Group{}
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopGroupsResponse_Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopGroupsResponse_Group) ProtoMessage() {}

func (x *GetTopGroupsResponse_Group) ProtoReflect() protoreflect.Message {
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopGroupsResponse_Group.ProtoReflect.Descriptor instead.
func (*GetTopGroupsResponse_Group) Descriptor() ([]byte, []int) {
	return file_errorgroups_v1_errorgroups_proto_rawDescGZIP(), []int{4, 0}
}

func (x *GetTopGroupsResponse_Group) GetHash() uint64 {
	if x != nil {
		return x.Hash
	}
	return 0
}

func (x *GetTopGroupsResponse_Group) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetTopGroupsResponse_Group) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GetTopGroupsResponse_Group) GetSeenTotal() uint64 {
	if x != nil {
		return x.SeenTotal
	}
	return 0
}

type GetHistRequest_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Custom        map[string]string      `protobuf:"bytes,1,rep,name=custom,proto3" json:"custom,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistRequest_Filter) Reset() {
	*x = GetHistRequest_Filter{}
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistRequest_Filter) ProtoMessage() {}

func (x *GetHistRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistRequest_Filter.ProtoReflect.Descriptor instead.
func (*GetHistRequest_Filter) Descriptor() ([]byte, []int) {
	return file_errorgroups_v1_errorgroups_proto_rawDescGZIP(), []int{5, 0}
}

func (x *GetHistRequest_Filter) GetCustom() map[string]string {
	if x != nil {
		return x.Custom
	}
	return nil
}

type GetDetailsRequest_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Custom        map[string]string      `protobuf:"bytes,1,rep,name=custom,proto3" json:"custom,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDetailsRequest_Filter) Reset() {
	*x = GetDetailsRequest_Filter{}
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDetailsRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetailsRequest_Filter) ProtoMessage() {}

func (x *GetDetailsRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetailsRequest_Filter.ProtoReflect.Descriptor instead.
func (*GetDetailsRequest_Filter) Descriptor() ([]byte, []int) {
	return file_errorgroups_v1_errorgroups_proto_rawDescGZIP(), []int{8, 0}
}

func (x *GetDetailsRequest_Filter) GetCustom() map[string]string {
	if x != nil {
		return x.Custom
	}
	return nil
}

type GetDetailsResponse_Distribution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Percent       uint64                 `protobuf:"varint,2,opt,name=percent,proto3" json:"percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDetailsResponse_Distribution) Reset() {
	*x = GetDetailsResponse_Distribution{}
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDetailsResponse_Distribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetailsResponse_Distribution) ProtoMessage() {}

func (x *GetDetailsResponse_Distribution) ProtoReflect() protoreflect.Message {
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetailsResponse_Distribution.ProtoReflect.Descriptor instead.
func (*GetDetailsResponse_Distribution) Descriptor() ([]byte, []int) {
	return file_errorgroups_v1_errorgroups_proto_rawDescGZIP(), []int{9, 0}
}

func (x *GetDetailsResponse_Distribution) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetDetailsResponse_Distribution) GetPercent() uint64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

type GetDetailsResponse_DistributionArray struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Array         []*GetDetailsResponse_Distribution `protobuf:"bytes,1,rep,name=array,proto3" json:"array,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDetailsResponse_DistributionArray) Reset() {
	*x = GetDetailsResponse_DistributionArray{}
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDetailsResponse_DistributionArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetailsResponse_DistributionArray) ProtoMessage() {}

func (x *GetDetailsResponse_DistributionArray) ProtoReflect() protoreflect.Message {
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetailsResponse_DistributionArray.ProtoReflect.Descriptor instead.
func (*GetDetailsResponse_DistributionArray) Descriptor() ([]byte, []int) {
	return file_errorgroups_v1_errorgroups_proto_rawDescGZIP(), []int{9, 1}
}

func (x *GetDetailsResponse_DistributionArray) GetArray() []*GetDetailsResponse_Distribution {
	if x != nil {
		return x.Array
	}
	return nil
}

type GetDetailsResponse_Distributions struct {
	state         protoimpl.MessageState                           `protogen:"open.v1"`
	ByEnv         []*GetDetailsResponse_Distribution               `protobuf:"bytes,1,rep,name=by_env,json=byEnv,proto3" json:"by_env,omitempty"`
	ByRelease     []*GetDetailsResponse_Distribution               `protobuf:"bytes,2,rep,name=by_release,json=byRelease,proto3" json:"by_release,omitempty"`
	BySource      []*GetDetailsResponse_Distribution               `protobuf:"bytes,3,rep,name=by_source,json=bySource,proto3" json:"by_source,omitempty"`
	ByService     []*GetDetailsResponse_Distribution               `protobuf:"bytes,4,rep,name=by_service,json=byService,proto3" json:"by_service,omitempty"`
	ByFilter      map[string]*GetDetailsResponse_DistributionArray `protobuf:"bytes,5,rep,name=by_filter,json=byFilter,proto3" json:"by_filter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDetailsResponse_Distributions) Reset() {
	*x = GetDetailsResponse_Distributions{}
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDetailsResponse_Distributions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetailsResponse_Distributions) ProtoMessage() {}

func (x *GetDetailsResponse_Distributions) ProtoReflect() protoreflect.Message {
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetailsResponse_Distributions.ProtoReflect.Descriptor instead.
func (*GetDetailsResponse_Distributions) Descriptor() ([]byte, []int) {
	return file_errorgroups_v1_errorgroups_proto_rawDescGZIP(), []int{9, 2}
}

func (x *GetDetailsResponse_Distributions) GetByEnv() []*GetDetailsResponse_Distribution {
	if x != nil {
		return x.ByEnv
	}
	return nil
}

func (x *GetDetailsResponse_Distributions) GetByRelease() []*GetDetailsResponse_Distribution {
	if x != nil {
		return x.ByRelease
	}
	return nil
}

func (x *GetDetailsResponse_Distributions) GetBySource() []*GetDetailsResponse_Distribution {
	if x != nil {
		return x.BySource
	}
	return nil
}

func (x *GetDetailsResponse_Distributions) GetByService() []*GetDetailsResponse_Distribution {
	if x != nil {
		return x.ByService
	}
	return nil
}

func (x *GetDetailsResponse_Distributions) GetByFilter() map[string]*GetDetailsResponse_DistributionArray {
	if x != nil {
		return x.ByFilter
	}
	return nil
}

type DiffByReleasesResponse_ReleaseInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeenTotal     uint64                 `protobuf:"varint,1,opt,name=seen_total,json=seenTotal,proto3" json:"seen_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffByReleasesResponse_ReleaseInfo) Reset() {
	*x = DiffByReleasesResponse_ReleaseInfo{}
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffByReleasesResponse_ReleaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffByReleasesResponse_ReleaseInfo) ProtoMessage() {}

func (x *DiffByReleasesResponse_ReleaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffByReleasesResponse_ReleaseInfo.ProtoReflect.Descriptor instead.
func (*DiffByReleasesResponse_ReleaseInfo) Descriptor() ([]byte, []int) {
	return file_errorgroups_v1_errorgroups_proto_rawDescGZIP(), []int{15, 0}
}

func (x *DiffByReleasesResponse_ReleaseInfo) GetSeenTotal() uint64 {
	if x != nil {
		return x.SeenTotal
	}
	return 0
}

type DiffByReleasesResponse_Group struct {
	state         protoimpl.MessageState                         `protogen:"open.v1"`
	Hash          uint64                                         `protobuf:"varint,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Message       string                                         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FirstSeenAt   *timestamppb.Timestamp                         `protobuf:"bytes,3,opt,name=first_seen_at,json=firstSeenAt,proto3" json:"first_seen_at,omitempty"`
	LastSeenAt    *timestamppb.Timestamp                         `protobuf:"bytes,4,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	Source        string                                         `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	ReleaseInfos  map[string]*DiffByReleasesResponse_ReleaseInfo `protobuf:"bytes,6,rep,name=release_infos,json=releaseInfos,proto3" json:"release_infos,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffByReleasesResponse_Group) Reset() {
	*x = DiffByReleasesResponse_Group{}
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffByReleasesResponse_Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffByReleasesResponse_Group) ProtoMessage() {}

func (x *DiffByReleasesResponse_Group) ProtoReflect() protoreflect.Message {
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffByReleasesResponse_Group.ProtoReflect.Descriptor instead.
func (*DiffByReleasesResponse_Group) Descriptor() ([]byte, []int) {
	return file_errorgroups_v1_errorgroups_proto_rawDescGZIP(), []int{15, 1}
}

func (x *DiffByReleasesResponse_Group) GetHash() uint64 {
	if x != nil {
		return x.Hash
	}
	return 0
}

func (x *DiffByReleasesResponse_Group) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DiffByReleasesResponse_Group) GetFirstSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeenAt
	}
	return nil
}

func (x *DiffByReleasesResponse_Group) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

func (x *DiffByReleasesResponse_Group) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *DiffByReleasesResponse_Group) GetReleaseInfos() map[string]*DiffByReleasesResponse_ReleaseInfo {
	if x != nil {
		return x.ReleaseInfos
	}
	return nil
}

type GetServiceFiltersResponse_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceFiltersResponse_Filter) Reset() {
	*x = GetServiceFiltersResponse_Filter{}
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceFiltersResponse_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceFiltersResponse_Filter) ProtoMessage() {}

func (x *GetServiceFiltersResponse_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_errorgroups_v1_errorgroups_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceFiltersResponse_Filter.ProtoReflect.Descriptor instead.
func (*GetServiceFiltersResponse_Filter) Descriptor() ([]byte, []int) {
	return file_errorgroups_v1_errorgroups_proto_rawDescGZIP(), []int{17, 0}
}

func (x *GetServiceFiltersResponse_Filter) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetServiceFiltersResponse_Filter) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_errorgroups_v1_errorgroups_proto protoreflect.FileDescriptor

const file_errorgroups_v1_errorgroups_proto_rawDesc = "" +
	"\n" +
	" errorgroups/v1/errorgroups.proto\x12\x0eerrorgroups.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9e\x01\n" +
	"\tTimeRange\x125\n" +
	"\bduration\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\bduration\x12.\n" +
	"\x04from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\"\x9c\x05\n" +
	"\x10GetGroupsRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x15\n" +
	"\x03env\x18\x02 \x01(\tH\x00R\x03env\x88\x01\x01\x12\x1d\n" +
	"\arelease\x18\x03 \x01(\tH\x01R\arelease\x88\x01\x01\x129\n" +
	"\bduration\x18\x04 \x01(\v2\x19.google.protobuf.DurationB\x02\x18\x01R\bduration\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\rR\x06offset\x12+\n" +
	"\x05order\x18\a \x01(\x0e2\x15.errorgroups.v1.OrderR\x05order\x12\x1d\n" +
	"\n" +
	"with_total\x18\b \x01(\bR\twithTotal\x12\x1b\n" +
	"\x06source\x18\t \x01(\tH\x02R\x06source\x88\x01\x01\x12D\n" +
	"\x06filter\x18\n" +
	" \x01(\v2'.errorgroups.v1.GetGroupsRequest.FilterH\x03R\x06filter\x88\x01\x01\x12=\n" +
	"\n" +
	"time_range\x18\v \x01(\v2\x19.errorgroups.v1.TimeRangeH\x04R\ttimeRange\x88\x01\x01\x1a\xa7\x01\n" +
	"\x06Filter\x12\x15\n" +
	"\x06is_new\x18\x01 \x01(\bR\x05isNew\x12K\n" +
	"\x06custom\x18\x02 \x03(\v23.errorgroups.v1.GetGroupsRequest.Filter.CustomEntryR\x06custom\x1a9\n" +
	"\vCustomEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x06\n" +
	"\x04_envB\n" +
	"\n" +
	"\b_releaseB\t\n" +
	"\a_sourceB\t\n" +
	"\a_filterB\r\n" +
	"\v_time_range\"\xd7\x02\n" +
	"\x11GetGroupsResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total\x12?\n" +
	"\x06groups\x18\x02 \x03(\v2'.errorgroups.v1.GetGroupsResponse.GroupR\x06groups\x1a\xea\x01\n" +
	"\x05Group\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\x04R\x04hash\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"seen_total\x18\x03 \x01(\x04R\tseenTotal\x12>\n" +
	"\rfirst_seen_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vfirstSeenAt\x12<\n" +
	"\flast_seen_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\"\xb2\x02\n" +
	"\x13GetTopGroupsRequest\x12\x15\n" +
	"\x03env\x18\x01 \x01(\tH\x00R\x03env\x88\x01\x01\x12\x1b\n" +
	"\x06source\x18\x02 \x01(\tH\x01R\x06source\x88\x01\x01\x129\n" +
	"\bduration\x18\x03 \x01(\v2\x19.google.protobuf.DurationB\x02\x18\x01R\bduration\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\rR\x06offset\x12\x1d\n" +
	"\n" +
	"with_total\x18\x06 \x01(\bR\twithTotal\x12=\n" +
	"\n" +
	"time_range\x18\a \x01(\v2\x19.errorgroups.v1.TimeRangeH\x02R\ttimeRange\x88\x01\x01B\x06\n" +
	"\x04_envB\t\n" +
	"\a_sourceB\r\n" +
	"\v_time_range\"\xde\x01\n" +
	"\x14GetTopGroupsResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total\x12B\n" +
	"\x06groups\x18\x02 \x03(\v2*.errorgroups.v1.GetTopGroupsResponse.GroupR\x06groups\x1al\n" +
	"\x05Group\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\x04R\x04hash\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"seen_total\x18\x04 \x01(\x04R\tseenTotal\"\xdb\x04\n" +
	"\x0eGetHistRequest\x12\x1d\n" +
	"\aservice\x18\x01 \x01(\tH\x00R\aservice\x88\x01\x01\x12\"\n" +
	"\n" +
	"group_hash\x18\x02 \x01(\x04H\x01R\tgroupHash\x88\x01\x01\x12\x15\n" +
	"\x03env\x18\x03 \x01(\tH\x02R\x03env\x88\x01\x01\x12\x1d\n" +
	"\arelease\x18\x04 \x01(\tH\x03R\arelease\x88\x01\x01\x12>\n" +
	"\bduration\x18\x05 \x01(\v2\x19.google.protobuf.DurationB\x02\x18\x01H\x04R\bduration\x88\x01\x01\x12\x1b\n" +
	"\x06source\x18\x06 \x01(\tH\x05R\x06source\x88\x01\x01\x12=\n" +
	"\n" +
	"time_range\x18\a \x01(\v2\x19.errorgroups.v1.TimeRangeH\x06R\ttimeRange\x88\x01\x01\x12B\n" +
	"\x06filter\x18\b \x01(\v2%.errorgroups.v1.GetHistRequest.FilterH\aR\x06filter\x88\x01\x01\x1a\x8e\x01\n" +
	"\x06Filter\x12I\n" +
	"\x06custom\x18\x01 \x03(\v21.errorgroups.v1.GetHistRequest.Filter.CustomEntryR\x06custom\x1a9\n" +
	"\vCustomEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\n" +
	"\n" +
	"\b_serviceB\r\n" +
	"\v_group_hashB\x06\n" +
	"\x04_envB\n" +
	"\n" +
	"\b_releaseB\v\n" +
	"\t_durationB\t\n" +
	"\a_sourceB\r\n" +
	"\v_time_rangeB\t\n" +
	"\a_filter\"_\n" +
	"\x0fGetHistResponse\x120\n" +
	"\abuckets\x18\x01 \x03(\v2\x16.errorgroups.v1.BucketR\abuckets\x12\x1a\n" +
	"\binterval\x18\x02 \x01(\x04R\binterval\"N\n" +
	"\x06Bucket\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\"\xb5\x03\n" +
	"\x11GetDetailsRequest\x12\x1d\n" +
	"\aservice\x18\x01 \x01(\tH\x00R\aservice\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"group_hash\x18\x02 \x01(\x04R\tgroupHash\x12\x15\n" +
	"\x03env\x18\x03 \x01(\tH\x01R\x03env\x88\x01\x01\x12\x1d\n" +
	"\arelease\x18\x04 \x01(\tH\x02R\arelease\x88\x01\x01\x12\x1b\n" +
	"\x06source\x18\x05 \x01(\tH\x03R\x06source\x88\x01\x01\x12E\n" +
	"\x06filter\x18\x06 \x01(\v2(.errorgroups.v1.GetDetailsRequest.FilterH\x04R\x06filter\x88\x01\x01\x1a\x91\x01\n" +
	"\x06Filter\x12L\n" +
	"\x06custom\x18\x01 \x03(\v24.errorgroups.v1.GetDetailsRequest.Filter.CustomEntryR\x06custom\x1a9\n" +
	"\vCustomEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\n" +
	"\n" +
	"\b_serviceB\x06\n" +
	"\x04_envB\n" +
	"\n" +
	"\b_releaseB\t\n" +
	"\a_sourceB\t\n" +
	"\a_filter\"\x96\t\n" +
	"\x12GetDetailsResponse\x12\x1d\n" +
	"\n" +
	"group_hash\x18\x01 \x01(\x04R\tgroupHash\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"seen_total\x18\x03 \x01(\x04R\tseenTotal\x12>\n" +
	"\rfirst_seen_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vfirstSeenAt\x12<\n" +
	"\flast_seen_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\x12V\n" +
	"\rdistributions\x18\x06 \x01(\v20.errorgroups.v1.GetDetailsResponse.DistributionsR\rdistributions\x12J\n" +
	"\blog_tags\x18\a \x03(\v2/.errorgroups.v1.GetDetailsResponse.LogTagsEntryR\alogTags\x12\x16\n" +
	"\x06source\x18\b \x01(\tR\x06source\x1a>\n" +
	"\fDistribution\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x18\n" +
	"\apercent\x18\x02 \x01(\x04R\apercent\x1aZ\n" +
	"\x11DistributionArray\x12E\n" +
	"\x05array\x18\x01 \x03(\v2/.errorgroups.v1.GetDetailsResponse.DistributionR\x05array\x1a\x95\x04\n" +
	"\rDistributions\x12F\n" +
	"\x06by_env\x18\x01 \x03(\v2/.errorgroups.v1.GetDetailsResponse.DistributionR\x05byEnv\x12N\n" +
	"\n" +
	"by_release\x18\x02 \x03(\v2/.errorgroups.v1.GetDetailsResponse.DistributionR\tbyRelease\x12L\n" +
	"\tby_source\x18\x03 \x03(\v2/.errorgroups.v1.GetDetailsResponse.DistributionR\bbySource\x12N\n" +
	"\n" +
	"by_service\x18\x04 \x03(\v2/.errorgroups.v1.GetDetailsResponse.DistributionR\tbyService\x12[\n" +
	"\tby_filter\x18\x05 \x03(\v2>.errorgroups.v1.GetDetailsResponse.Distributions.ByFilterEntryR\bbyFilter\x1aq\n" +
	"\rByFilterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12J\n" +
	"\x05value\x18\x02 \x01(\v24.errorgroups.v1.GetDetailsResponse.DistributionArrayR\x05value:\x028\x01\x1a:\n" +
	"\fLogTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"S\n" +
	"\x12GetReleasesRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x15\n" +
	"\x03env\x18\x03 \x01(\tH\x00R\x03env\x88\x01\x01B\x06\n" +
	"\x04_envJ\x04\b\x02\x10\x03\"1\n" +
	"\x13GetReleasesResponse\x12\x1a\n" +
	"\breleases\x18\x01 \x03(\tR\breleases\"w\n" +
	"\x12GetServicesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x15\n" +
	"\x03env\x18\x02 \x01(\tH\x00R\x03env\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\rR\x06offsetB\x06\n" +
	"\x04_env\"1\n" +
	"\x13GetServicesResponse\x12\x1a\n" +
	"\bservices\x18\x01 \x03(\tR\bservices\"\x8e\x02\n" +
	"\x15DiffByReleasesRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1a\n" +
	"\breleases\x18\x02 \x03(\tR\breleases\x12\x15\n" +
	"\x03env\x18\x03 \x01(\tH\x00R\x03env\x88\x01\x01\x12\x1b\n" +
	"\x06source\x18\x04 \x01(\tH\x01R\x06source\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\rR\x06offset\x12+\n" +
	"\x05order\x18\a \x01(\x0e2\x15.errorgroups.v1.OrderR\x05order\x12\x1d\n" +
	"\n" +
	"with_total\x18\b \x01(\bR\twithTotalB\x06\n" +
	"\x04_envB\t\n" +
	"\a_source\"\xca\x04\n" +
	"\x16DiffByReleasesResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total\x12D\n" +
	"\x06groups\x18\x02 \x03(\v2,.errorgroups.v1.DiffByReleasesResponse.GroupR\x06groups\x1a,\n" +
	"\vReleaseInfo\x12\x1d\n" +
	"\n" +
	"seen_total\x18\x01 \x01(\x04R\tseenTotal\x1a\xa5\x03\n" +
	"\x05Group\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\x04R\x04hash\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12>\n" +
	"\rfirst_seen_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vfirstSeenAt\x12<\n" +
	"\flast_seen_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12c\n" +
	"\rrelease_infos\x18\x06 \x03(\v2>.errorgroups.v1.DiffByReleasesResponse.Group.ReleaseInfosEntryR\freleaseInfos\x1as\n" +
	"\x11ReleaseInfosEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12H\n" +
	"\x05value\x18\x02 \x01(\v22.errorgroups.v1.DiffByReleasesResponse.ReleaseInfoR\x05value:\x028\x01\"S\n" +
	"\x18GetServiceFiltersRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x15\n" +
	"\x03env\x18\x02 \x01(\tH\x00R\x03env\x88\x01\x01B\x06\n" +
	"\x04_env\"\x9b\x01\n" +
	"\x19GetServiceFiltersResponse\x12J\n" +
	"\afilters\x18\x01 \x03(\v20.errorgroups.v1.GetServiceFiltersResponse.FilterR\afilters\x1a2\n" +
	"\x06Filter\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values*?\n" +
	"\x05Order\x12\x12\n" +
	"\x0eORDER_FREQUENT\x10\x00\x12\x10\n" +
	"\fORDER_LATEST\x10\x01\x12\x10\n" +
	"\fORDER_OLDEST\x10\x022\xed\x05\n" +
	"\x12ErrorGroupsService\x12R\n" +
	"\tGetGroups\x12 .errorgroups.v1.GetGroupsRequest\x1a!.errorgroups.v1.GetGroupsResponse\"\x00\x12[\n" +
	"\fGetTopGroups\x12#.errorgroups.v1.GetTopGroupsRequest\x1a$.errorgroups.v1.GetTopGroupsResponse\"\x00\x12L\n" +
	"\aGetHist\x12\x1e.errorgroups.v1.GetHistRequest\x1a\x1f.errorgroups.v1.GetHistResponse\"\x00\x12U\n" +
	"\n" +
	"GetDetails\x12!.errorgroups.v1.GetDetailsRequest\x1a\".errorgroups.v1.GetDetailsResponse\"\x00\x12X\n" +
	"\vGetReleases\x12\".errorgroups.v1.GetReleasesRequest\x1a#.errorgroups.v1.GetReleasesResponse\"\x00\x12X\n" +
	"\vGetServices\x12\".errorgroups.v1.GetServicesRequest\x1a#.errorgroups.v1.GetServicesResponse\"\x00\x12a\n" +
	"\x0eDiffByReleases\x12%.errorgroups.v1.DiffByReleasesRequest\x1a&.errorgroups.v1.DiffByReleasesResponse\"\x00\x12j\n" +
	"\x11GetServiceFilters\x12(.errorgroups.v1.GetServiceFiltersRequest\x1a).errorgroups.v1.GetServiceFiltersResponse\"\x00B;Z9github.com/ozontech/seq-ui/pkg/errorgroups/v1;errorgroupsb\x06proto3"

var (
	file_errorgroups_v1_errorgroups_proto_rawDescOnce sync.Once
	file_errorgroups_v1_errorgroups_proto_rawDescData []byte
)

func file_errorgroups_v1_errorgroups_proto_rawDescGZIP() []byte {
	file_errorgroups_v1_errorgroups_proto_rawDescOnce.Do(func() {
		file_errorgroups_v1_errorgroups_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_errorgroups_v1_errorgroups_proto_rawDesc), len(file_errorgroups_v1_errorgroups_proto_rawDesc)))
	})
	return file_errorgroups_v1_errorgroups_proto_rawDescData
}

var file_errorgroups_v1_errorgroups_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_errorgroups_v1_errorgroups_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_errorgroups_v1_errorgroups_proto_goTypes = []any{
	(Order)(0),                                   // 0: errorgroups.v1.Order
	(*TimeRange)(nil),                            // 1: errorgroups.v1.TimeRange
	(*GetGroupsRequest)(nil),                     // 2: errorgroups.v1.GetGroupsRequest
	(*GetGroupsResponse)(nil),                    // 3: errorgroups.v1.GetGroupsResponse
	(*GetTopGroupsRequest)(nil),                  // 4: errorgroups.v1.GetTopGroupsRequest
	(*GetTopGroupsResponse)(nil),                 // 5: errorgroups.v1.GetTopGroupsResponse
	(*GetHistRequest)(nil),                       // 6: errorgroups.v1.GetHistRequest
	(*GetHistResponse)(nil),                      // 7: errorgroups.v1.GetHistResponse
	(*Bucket)(nil),                               // 8: errorgroups.v1.Bucket
	(*GetDetailsRequest)(nil),                    // 9: errorgroups.v1.GetDetailsRequest
	(*GetDetailsResponse)(nil),                   // 10: errorgroups.v1.GetDetailsResponse
	(*GetReleasesRequest)(nil),                   // 11: errorgroups.v1.GetReleasesRequest
	(*GetReleasesResponse)(nil),                  // 12: errorgroups.v1.GetReleasesResponse
	(*GetServicesRequest)(nil),                   // 13: errorgroups.v1.GetServicesRequest
	(*GetServicesResponse)(nil),                  // 14: errorgroups.v1.GetServicesResponse
	(*DiffByReleasesRequest)(nil),                // 15: errorgroups.v1.DiffByReleasesRequest
	(*DiffByReleasesResponse)(nil),               // 16: errorgroups.v1.DiffByReleasesResponse
	(*GetServiceFiltersRequest)(nil),             // 17: errorgroups.v1.GetServiceFiltersRequest
	(*GetServiceFiltersResponse)(nil),            // 18: errorgroups.v1.GetServiceFiltersResponse
	(*GetGroupsRequest_Filter)(nil),              // 19: errorgroups.v1.GetGroupsRequest.Filter
	nil,                                          // 20: errorgroups.v1.GetGroupsRequest.Filter.CustomEntry
	(*GetGroupsResponse_Group)(nil),              // 21: errorgroups.v1.GetGroupsResponse.Group
	(*GetTopGroupsResponse_Group)(nil),           // 22: errorgroups.v1.GetTopGroupsResponse.Group
	(*GetHistRequest_Filter)(nil),                // 23: errorgroups.v1.GetHistRequest.Filter
	nil,                                          // 24: errorgroups.v1.GetHistRequest.Filter.CustomEntry
	(*GetDetailsRequest_Filter)(nil),             // 25: errorgroups.v1.GetDetailsRequest.Filter
	nil,                                          // 26: errorgroups.v1.GetDetailsRequest.Filter.CustomEntry
	(*GetDetailsResponse_Distribution)(nil),      // 27: errorgroups.v1.GetDetailsResponse.Distribution
	(*GetDetailsResponse_DistributionArray)(nil), // 28: errorgroups.v1.GetDetailsResponse.DistributionArray
	(*GetDetailsResponse_Distributions)(nil),     // 29: errorgroups.v1.GetDetailsResponse.Distributions
	nil,                                          // 30: errorgroups.v1.GetDetailsResponse.LogTagsEntry
	nil,                                          // 31: errorgroups.v1.GetDetailsResponse.Distributions.ByFilterEntry
	(*DiffByReleasesResponse_ReleaseInfo)(nil),   // 32: errorgroups.v1.DiffByReleasesResponse.ReleaseInfo
	(*DiffByReleasesResponse_Group)(nil),         // 33: errorgroups.v1.DiffByReleasesResponse.Group
	nil,                                          // 34: errorgroups.v1.DiffByReleasesResponse.Group.ReleaseInfosEntry
	(*GetServiceFiltersResponse_Filter)(nil),     // 35: errorgroups.v1.GetServiceFiltersResponse.Filter
	(*durationpb.Duration)(nil),                  // 36: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),                // 37: google.protobuf.Timestamp
}
var file_errorgroups_v1_errorgroups_proto_depIdxs = []int32{
	36, // 0: errorgroups.v1.TimeRange.duration:type_name -> google.protobuf.Duration
	37, // 1: errorgroups.v1.TimeRange.from:type_name -> google.protobuf.Timestamp
	37, // 2: errorgroups.v1.TimeRange.to:type_name -> google.protobuf.Timestamp
	36, // 3: errorgroups.v1.GetGroupsRequest.duration:type_name -> google.protobuf.Duration
	0,  // 4: errorgroups.v1.GetGroupsRequest.order:type_name -> errorgroups.v1.Order
	19, // 5: errorgroups.v1.GetGroupsRequest.filter:type_name -> errorgroups.v1.GetGroupsRequest.Filter
	1,  // 6: errorgroups.v1.GetGroupsRequest.time_range:type_name -> errorgroups.v1.TimeRange
	21, // 7: errorgroups.v1.GetGroupsResponse.groups:type_name -> errorgroups.v1.GetGroupsResponse.Group
	36, // 8: errorgroups.v1.GetTopGroupsRequest.duration:type_name -> google.protobuf.Duration
	1,  // 9: errorgroups.v1.GetTopGroupsRequest.time_range:type_name -> errorgroups.v1.TimeRange
	22, // 10: errorgroups.v1.GetTopGroupsResponse.groups:type_name -> errorgroups.v1.GetTopGroupsResponse.Group
	36, // 11: errorgroups.v1.GetHistRequest.duration:type_name -> google.protobuf.Duration
	1,  // 12: errorgroups.v1.GetHistRequest.time_range:type_name -> errorgroups.v1.TimeRange
	23, // 13: errorgroups.v1.GetHistRequest.filter:type_name -> errorgroups.v1.GetHistRequest.Filter
	8,  // 14: errorgroups.v1.GetHistResponse.buckets:type_name -> errorgroups.v1.Bucket
	37, // 15: errorgroups.v1.Bucket.time:type_name -> google.protobuf.Timestamp
	25, // 16: errorgroups.v1.GetDetailsRequest.filter:type_name -> errorgroups.v1.GetDetailsRequest.Filter
	37, // 17: errorgroups.v1.GetDetailsResponse.first_seen_at:type_name -> google.protobuf.Timestamp
	37, // 18: errorgroups.v1.GetDetailsResponse.last_seen_at:type_name -> google.protobuf.Timestamp
	29, // 19: errorgroups.v1.GetDetailsResponse.distributions:type_name -> errorgroups.v1.GetDetailsResponse.Distributions
	30, // 20: errorgroups.v1.GetDetailsResponse.log_tags:type_name -> errorgroups.v1.GetDetailsResponse.LogTagsEntry
	0,  // 21: errorgroups.v1.DiffByReleasesRequest.order:type_name -> errorgroups.v1.Order
	33, // 22: errorgroups.v1.DiffByReleasesResponse.groups:type_name -> errorgroups.v1.DiffByReleasesResponse.Group
	35, // 23: errorgroups.v1.GetServiceFiltersResponse.filters:type_name -> errorgroups.v1.GetServiceFiltersResponse.Filter
	20, // 24: errorgroups.v1.GetGroupsRequest.Filter.custom:type_name -> errorgroups.v1.GetGroupsRequest.Filter.CustomEntry
	37, // 25: errorgroups.v1.GetGroupsResponse.Group.first_seen_at:type_name -> google.protobuf.Timestamp
	37, // 26: errorgroups.v1.GetGroupsResponse.Group.last_seen_at:type_name -> google.protobuf.Timestamp
	24, // 27: errorgroups.v1.GetHistRequest.Filter.custom:type_name -> errorgroups.v1.GetHistRequest.Filter.CustomEntry
	26, // 28: errorgroups.v1.GetDetailsRequest.Filter.custom:type_name -> errorgroups.v1.GetDetailsRequest.Filter.CustomEntry
	27, // 29: errorgroups.v1.GetDetailsResponse.DistributionArray.array:type_name -> errorgroups.v1.GetDetailsResponse.Distribution
	27, // 30: errorgroups.v1.GetDetailsResponse.Distributions.by_env:type_name -> errorgroups.v1.GetDetailsResponse.Distribution
	27, // 31: errorgroups.v1.GetDetailsResponse.Distributions.by_release:type_name -> errorgroups.v1.GetDetailsResponse.Distribution
	27, // 32: errorgroups.v1.GetDetailsResponse.Distributions.by_source:type_name -> errorgroups.v1.GetDetailsResponse.Distribution
	27, // 33: errorgroups.v1.GetDetailsResponse.Distributions.by_service:type_name -> errorgroups.v1.GetDetailsResponse.Distribution
	31, // 34: errorgroups.v1.GetDetailsResponse.Distributions.by_filter:type_name -> errorgroups.v1.GetDetailsResponse.Distributions.ByFilterEntry
	28, // 35: errorgroups.v1.GetDetailsResponse.Distributions.ByFilterEntry.value:type_name -> errorgroups.v1.GetDetailsResponse.DistributionArray
	37, // 36: errorgroups.v1.DiffByReleasesResponse.Group.first_seen_at:type_name -> google.protobuf.Timestamp
	37, // 37: errorgroups.v1.DiffByReleasesResponse.Group.last_seen_at:type_name -> google.protobuf.Timestamp
	34, // 38: errorgroups.v1.DiffByReleasesResponse.Group.release_infos:type_name -> errorgroups.v1.DiffByReleasesResponse.Group.ReleaseInfosEntry
	32, // 39: errorgroups.v1.DiffByReleasesResponse.Group.ReleaseInfosEntry.value:type_name -> errorgroups.v1.DiffByReleasesResponse.ReleaseInfo
	2,  // 40: errorgroups.v1.ErrorGroupsService.GetGroups:input_type -> errorgroups.v1.GetGroupsRequest
	4,  // 41: errorgroups.v1.ErrorGroupsService.GetTopGroups:input_type -> errorgroups.v1.GetTopGroupsRequest
	6,  // 42: errorgroups.v1.ErrorGroupsService.GetHist:input_type -> errorgroups.v1.GetHistRequest
	9,  // 43: errorgroups.v1.ErrorGroupsService.GetDetails:input_type -> errorgroups.v1.GetDetailsRequest
	11, // 44: errorgroups.v1.ErrorGroupsService.GetReleases:input_type -> errorgroups.v1.GetReleasesRequest
	13, // 45: errorgroups.v1.ErrorGroupsService.GetServices:input_type -> errorgroups.v1.GetServicesRequest
	15, // 46: errorgroups.v1.ErrorGroupsService.DiffByReleases:input_type -> errorgroups.v1.DiffByReleasesRequest
	17, // 47: errorgroups.v1.ErrorGroupsService.GetServiceFilters:input_type -> errorgroups.v1.GetServiceFiltersRequest
	3,  // 48: errorgroups.v1.ErrorGroupsService.GetGroups:output_type -> errorgroups.v1.GetGroupsResponse
	5,  // 49: errorgroups.v1.ErrorGroupsService.GetTopGroups:output_type -> errorgroups.v1.GetTopGroupsResponse
	7,  // 50: errorgroups.v1.ErrorGroupsService.GetHist:output_type -> errorgroups.v1.GetHistResponse
	10, // 51: errorgroups.v1.ErrorGroupsService.GetDetails:output_type -> errorgroups.v1.GetDetailsResponse
	12, // 52: errorgroups.v1.ErrorGroupsService.GetReleases:output_type -> errorgroups.v1.GetReleasesResponse
	14, // 53: errorgroups.v1.ErrorGroupsService.GetServices:output_type -> errorgroups.v1.GetServicesResponse
	16, // 54: errorgroups.v1.ErrorGroupsService.DiffByReleases:output_type -> errorgroups.v1.DiffByReleasesResponse
	18, // 55: errorgroups.v1.ErrorGroupsService.GetServiceFilters:output_type -> errorgroups.v1.GetServiceFiltersResponse
	48, // [48:56] is the sub-list for method output_type
	40, // [40:48] is the sub-list for method input_type
	40, // [40:40] is the sub-list for extension type_name
	40, // [40:40] is the sub-list for extension extendee
	0,  // [0:40] is the sub-list for field type_name
}

func init() { file_errorgroups_v1_errorgroups_proto_init() }
func file_errorgroups_v1_errorgroups_proto_init() {
	if File_errorgroups_v1_errorgroups_proto != nil {
		return
	}
	file_errorgroups_v1_errorgroups_proto_msgTypes[1].OneofWrappers = []any{}
	file_errorgroups_v1_errorgroups_proto_msgTypes[3].OneofWrappers = []any{}
	file_errorgroups_v1_errorgroups_proto_msgTypes[5].OneofWrappers = []any{}
	file_errorgroups_v1_errorgroups_proto_msgTypes[8].OneofWrappers = []any{}
	file_errorgroups_v1_errorgroups_proto_msgTypes[10].OneofWrappers = []any{}
	file_errorgroups_v1_errorgroups_proto_msgTypes[12].OneofWrappers = []any{}
	file_errorgroups_v1_errorgroups_proto_msgTypes[14].OneofWrappers = []any{}
	file_errorgroups_v1_errorgroups_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errorgroups_v1_errorgroups_proto_rawDesc), len(file_errorgroups_v1_errorgroups_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_errorgroups_v1_errorgroups_proto_goTypes,
		DependencyIndexes: file_errorgroups_v1_errorgroups_proto_depIdxs,
		EnumInfos:         file_errorgroups_v1_errorgroups_proto_enumTypes,
		MessageInfos:      file_errorgroups_v1_errorgroups_proto_msgTypes,
	}.Build()
	File_errorgroups_v1_errorgroups_proto = out.File
	file_errorgroups_v1_errorgroups_proto_goTypes = nil
	file_errorgroups_v1_errorgroups_proto_depIdxs = nil
}
