// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ozontech/seq-ui/internal/pkg/service/userprofile (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=internal/pkg/service/userprofile/mock/service.go github.com/ozontech/seq-ui/internal/pkg/service/userprofile Service
//

// Package mock_userprofiles is a generated GoMock package.
package mock_userprofiles

import (
	context "context"
	reflect "reflect"

	types "github.com/ozontech/seq-ui/internal/app/types"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// DeleteFavoriteQuery mocks base method.
func (m *MockService) DeleteFavoriteQuery(arg0 context.Context, arg1 types.DeleteFavoriteQueryRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFavoriteQuery", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFavoriteQuery indicates an expected call of DeleteFavoriteQuery.
func (mr *MockServiceMockRecorder) DeleteFavoriteQuery(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFavoriteQuery", reflect.TypeOf((*MockService)(nil).DeleteFavoriteQuery), arg0, arg1)
}

// GetFavoriteQueries mocks base method.
func (m *MockService) GetFavoriteQueries(arg0 context.Context, arg1 types.GetFavoriteQueriesRequest) (types.FavoriteQueries, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFavoriteQueries", arg0, arg1)
	ret0, _ := ret[0].(types.FavoriteQueries)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFavoriteQueries indicates an expected call of GetFavoriteQueries.
func (mr *MockServiceMockRecorder) GetFavoriteQueries(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavoriteQueries", reflect.TypeOf((*MockService)(nil).GetFavoriteQueries), arg0, arg1)
}

// GetOrCreateFavoriteQuery mocks base method.
func (m *MockService) GetOrCreateFavoriteQuery(arg0 context.Context, arg1 types.GetOrCreateFavoriteQueryRequest) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateFavoriteQuery", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreateFavoriteQuery indicates an expected call of GetOrCreateFavoriteQuery.
func (mr *MockServiceMockRecorder) GetOrCreateFavoriteQuery(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateFavoriteQuery", reflect.TypeOf((*MockService)(nil).GetOrCreateFavoriteQuery), arg0, arg1)
}

// GetOrCreateUserProfile mocks base method.
func (m *MockService) GetOrCreateUserProfile(arg0 context.Context, arg1 types.GetOrCreateUserProfileRequest) (types.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateUserProfile", arg0, arg1)
	ret0, _ := ret[0].(types.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreateUserProfile indicates an expected call of GetOrCreateUserProfile.
func (mr *MockServiceMockRecorder) GetOrCreateUserProfile(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateUserProfile", reflect.TypeOf((*MockService)(nil).GetOrCreateUserProfile), arg0, arg1)
}

// UpdateUserProfile mocks base method.
func (m *MockService) UpdateUserProfile(arg0 context.Context, arg1 types.UpdateUserProfileRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserProfile", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserProfile indicates an expected call of UpdateUserProfile.
func (mr *MockServiceMockRecorder) UpdateUserProfile(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserProfile", reflect.TypeOf((*MockService)(nil).UpdateUserProfile), arg0, arg1)
}
