// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ozontech/seq-ui/internal/pkg/client/seqdb/seqproxyapi/v1 (interfaces: SeqProxyApi_FetchClient,SeqProxyApi_ExportClient,SeqProxyApi_ExportAsyncSearchClient)
//
// Generated by this command:
//
//	mockgen -destination=internal/pkg/client/seqdb/seqproxyapi/v1/mock/seq_proxy_api_grpc_streams.go -package=mock_seqproxyapi github.com/ozontech/seq-ui/internal/pkg/client/seqdb/seqproxyapi/v1 SeqProxyApi_FetchClient,SeqProxyApi_ExportClient,SeqProxyApi_ExportAsyncSearchClient
//

// Package mock_seqproxyapi is a generated GoMock package.
package mock_seqproxyapi

import (
	context "context"
	reflect "reflect"

	seqproxyapi "github.com/ozontech/seq-ui/internal/pkg/client/seqdb/seqproxyapi/v1"
	gomock "go.uber.org/mock/gomock"
	metadata "google.golang.org/grpc/metadata"
)

// MockSeqProxyApi_FetchClient is a mock of SeqProxyApi_FetchClient interface.
type MockSeqProxyApi_FetchClient[Res any] struct {
	ctrl     *gomock.Controller
	recorder *MockSeqProxyApi_FetchClientMockRecorder[Res]
	isgomock struct{}
}

// MockSeqProxyApi_FetchClientMockRecorder is the mock recorder for MockSeqProxyApi_FetchClient.
type MockSeqProxyApi_FetchClientMockRecorder[Res any] struct {
	mock *MockSeqProxyApi_FetchClient[Res]
}

// NewMockSeqProxyApi_FetchClient creates a new mock instance.
func NewMockSeqProxyApi_FetchClient[Res any](ctrl *gomock.Controller) *MockSeqProxyApi_FetchClient[Res] {
	mock := &MockSeqProxyApi_FetchClient[Res]{ctrl: ctrl}
	mock.recorder = &MockSeqProxyApi_FetchClientMockRecorder[Res]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeqProxyApi_FetchClient[Res]) EXPECT() *MockSeqProxyApi_FetchClientMockRecorder[Res] {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockSeqProxyApi_FetchClient[Res]) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockSeqProxyApi_FetchClientMockRecorder[Res]) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockSeqProxyApi_FetchClient[Res])(nil).CloseSend))
}

// Context mocks base method.
func (m *MockSeqProxyApi_FetchClient[Res]) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockSeqProxyApi_FetchClientMockRecorder[Res]) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockSeqProxyApi_FetchClient[Res])(nil).Context))
}

// Header mocks base method.
func (m *MockSeqProxyApi_FetchClient[Res]) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockSeqProxyApi_FetchClientMockRecorder[Res]) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockSeqProxyApi_FetchClient[Res])(nil).Header))
}

// Recv mocks base method.
func (m *MockSeqProxyApi_FetchClient[Res]) Recv() (*seqproxyapi.Document, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*seqproxyapi.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockSeqProxyApi_FetchClientMockRecorder[Res]) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockSeqProxyApi_FetchClient[Res])(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockSeqProxyApi_FetchClient[Res]) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockSeqProxyApi_FetchClientMockRecorder[Res]) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockSeqProxyApi_FetchClient[Res])(nil).RecvMsg), m)
}

// SendMsg mocks base method.
func (m_2 *MockSeqProxyApi_FetchClient[Res]) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockSeqProxyApi_FetchClientMockRecorder[Res]) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockSeqProxyApi_FetchClient[Res])(nil).SendMsg), m)
}

// Trailer mocks base method.
func (m *MockSeqProxyApi_FetchClient[Res]) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockSeqProxyApi_FetchClientMockRecorder[Res]) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockSeqProxyApi_FetchClient[Res])(nil).Trailer))
}

// MockSeqProxyApi_ExportClient is a mock of SeqProxyApi_ExportClient interface.
type MockSeqProxyApi_ExportClient[Res any] struct {
	ctrl     *gomock.Controller
	recorder *MockSeqProxyApi_ExportClientMockRecorder[Res]
	isgomock struct{}
}

// MockSeqProxyApi_ExportClientMockRecorder is the mock recorder for MockSeqProxyApi_ExportClient.
type MockSeqProxyApi_ExportClientMockRecorder[Res any] struct {
	mock *MockSeqProxyApi_ExportClient[Res]
}

// NewMockSeqProxyApi_ExportClient creates a new mock instance.
func NewMockSeqProxyApi_ExportClient[Res any](ctrl *gomock.Controller) *MockSeqProxyApi_ExportClient[Res] {
	mock := &MockSeqProxyApi_ExportClient[Res]{ctrl: ctrl}
	mock.recorder = &MockSeqProxyApi_ExportClientMockRecorder[Res]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeqProxyApi_ExportClient[Res]) EXPECT() *MockSeqProxyApi_ExportClientMockRecorder[Res] {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockSeqProxyApi_ExportClient[Res]) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockSeqProxyApi_ExportClientMockRecorder[Res]) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockSeqProxyApi_ExportClient[Res])(nil).CloseSend))
}

// Context mocks base method.
func (m *MockSeqProxyApi_ExportClient[Res]) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockSeqProxyApi_ExportClientMockRecorder[Res]) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockSeqProxyApi_ExportClient[Res])(nil).Context))
}

// Header mocks base method.
func (m *MockSeqProxyApi_ExportClient[Res]) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockSeqProxyApi_ExportClientMockRecorder[Res]) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockSeqProxyApi_ExportClient[Res])(nil).Header))
}

// Recv mocks base method.
func (m *MockSeqProxyApi_ExportClient[Res]) Recv() (*seqproxyapi.ExportResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*seqproxyapi.ExportResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockSeqProxyApi_ExportClientMockRecorder[Res]) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockSeqProxyApi_ExportClient[Res])(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockSeqProxyApi_ExportClient[Res]) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockSeqProxyApi_ExportClientMockRecorder[Res]) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockSeqProxyApi_ExportClient[Res])(nil).RecvMsg), m)
}

// SendMsg mocks base method.
func (m_2 *MockSeqProxyApi_ExportClient[Res]) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockSeqProxyApi_ExportClientMockRecorder[Res]) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockSeqProxyApi_ExportClient[Res])(nil).SendMsg), m)
}

// Trailer mocks base method.
func (m *MockSeqProxyApi_ExportClient[Res]) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockSeqProxyApi_ExportClientMockRecorder[Res]) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockSeqProxyApi_ExportClient[Res])(nil).Trailer))
}

// MockSeqProxyApi_ExportAsyncSearchClient is a mock of SeqProxyApi_ExportAsyncSearchClient interface.
type MockSeqProxyApi_ExportAsyncSearchClient[Res any] struct {
	ctrl     *gomock.Controller
	recorder *MockSeqProxyApi_ExportAsyncSearchClientMockRecorder[Res]
	isgomock struct{}
}

// MockSeqProxyApi_ExportAsyncSearchClientMockRecorder is the mock recorder for MockSeqProxyApi_ExportAsyncSearchClient.
type MockSeqProxyApi_ExportAsyncSearchClientMockRecorder[Res any] struct {
	mock *MockSeqProxyApi_ExportAsyncSearchClient[Res]
}

// NewMockSeqProxyApi_ExportAsyncSearchClient creates a new mock instance.
func NewMockSeqProxyApi_ExportAsyncSearchClient[Res any](ctrl *gomock.Controller) *MockSeqProxyApi_ExportAsyncSearchClient[Res] {
	mock := &MockSeqProxyApi_ExportAsyncSearchClient[Res]{ctrl: ctrl}
	mock.recorder = &MockSeqProxyApi_ExportAsyncSearchClientMockRecorder[Res]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeqProxyApi_ExportAsyncSearchClient[Res]) EXPECT() *MockSeqProxyApi_ExportAsyncSearchClientMockRecorder[Res] {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockSeqProxyApi_ExportAsyncSearchClient[Res]) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockSeqProxyApi_ExportAsyncSearchClientMockRecorder[Res]) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockSeqProxyApi_ExportAsyncSearchClient[Res])(nil).CloseSend))
}

// Context mocks base method.
func (m *MockSeqProxyApi_ExportAsyncSearchClient[Res]) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockSeqProxyApi_ExportAsyncSearchClientMockRecorder[Res]) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockSeqProxyApi_ExportAsyncSearchClient[Res])(nil).Context))
}

// Header mocks base method.
func (m *MockSeqProxyApi_ExportAsyncSearchClient[Res]) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockSeqProxyApi_ExportAsyncSearchClientMockRecorder[Res]) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockSeqProxyApi_ExportAsyncSearchClient[Res])(nil).Header))
}

// Recv mocks base method.
func (m *MockSeqProxyApi_ExportAsyncSearchClient[Res]) Recv() (*seqproxyapi.ExportResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*seqproxyapi.ExportResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockSeqProxyApi_ExportAsyncSearchClientMockRecorder[Res]) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockSeqProxyApi_ExportAsyncSearchClient[Res])(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockSeqProxyApi_ExportAsyncSearchClient[Res]) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockSeqProxyApi_ExportAsyncSearchClientMockRecorder[Res]) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockSeqProxyApi_ExportAsyncSearchClient[Res])(nil).RecvMsg), m)
}

// SendMsg mocks base method.
func (m_2 *MockSeqProxyApi_ExportAsyncSearchClient[Res]) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockSeqProxyApi_ExportAsyncSearchClientMockRecorder[Res]) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockSeqProxyApi_ExportAsyncSearchClient[Res])(nil).SendMsg), m)
}

// Trailer mocks base method.
func (m *MockSeqProxyApi_ExportAsyncSearchClient[Res]) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockSeqProxyApi_ExportAsyncSearchClientMockRecorder[Res]) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockSeqProxyApi_ExportAsyncSearchClient[Res])(nil).Trailer))
}
