// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ozontech/seq-ui/internal/pkg/client/seqdb/seqproxyapi/v1 (interfaces: SeqProxyApiClient,SeqProxyApiServer,UnsafeSeqProxyApiServer,SeqProxyApi_FetchServer,SeqProxyApi_ExportServer,SeqProxyApi_ExportAsyncSearchServer,SeqProxyApi_FetchClient,SeqProxyApi_ExportClient,SeqProxyApi_ExportAsyncSearchClient)
//
// Generated by this command:
//
//	mockgen -destination=internal/pkg/client/seqdb/seqproxyapi/v1/mock/seq_proxy_api_grpc.pb.go -package=mock_seqproxyapi github.com/ozontech/seq-ui/internal/pkg/client/seqdb/seqproxyapi/v1 SeqProxyApiClient,SeqProxyApiServer,UnsafeSeqProxyApiServer,SeqProxyApi_FetchServer,SeqProxyApi_ExportServer,SeqProxyApi_ExportAsyncSearchServer,SeqProxyApi_FetchClient,SeqProxyApi_ExportClient,SeqProxyApi_ExportAsyncSearchClient
//

// Package mock_seqproxyapi is a generated GoMock package.
package mock_seqproxyapi

import (
	context "context"
	reflect "reflect"

	seqproxyapi "github.com/ozontech/seq-ui/internal/pkg/client/seqdb/seqproxyapi/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
	metadata "google.golang.org/grpc/metadata"
)

// MockSeqProxyApiClient is a mock of SeqProxyApiClient interface.
type MockSeqProxyApiClient struct {
	ctrl     *gomock.Controller
	recorder *MockSeqProxyApiClientMockRecorder
	isgomock struct{}
}

// MockSeqProxyApiClientMockRecorder is the mock recorder for MockSeqProxyApiClient.
type MockSeqProxyApiClientMockRecorder struct {
	mock *MockSeqProxyApiClient
}

// NewMockSeqProxyApiClient creates a new mock instance.
func NewMockSeqProxyApiClient(ctrl *gomock.Controller) *MockSeqProxyApiClient {
	mock := &MockSeqProxyApiClient{ctrl: ctrl}
	mock.recorder = &MockSeqProxyApiClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeqProxyApiClient) EXPECT() *MockSeqProxyApiClientMockRecorder {
	return m.recorder
}

// CancelAsyncSearch mocks base method.
func (m *MockSeqProxyApiClient) CancelAsyncSearch(ctx context.Context, in *seqproxyapi.CancelAsyncSearchRequest, opts ...grpc.CallOption) (*seqproxyapi.CancelAsyncSearchResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CancelAsyncSearch", varargs...)
	ret0, _ := ret[0].(*seqproxyapi.CancelAsyncSearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelAsyncSearch indicates an expected call of CancelAsyncSearch.
func (mr *MockSeqProxyApiClientMockRecorder) CancelAsyncSearch(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelAsyncSearch", reflect.TypeOf((*MockSeqProxyApiClient)(nil).CancelAsyncSearch), varargs...)
}

// ComplexSearch mocks base method.
func (m *MockSeqProxyApiClient) ComplexSearch(ctx context.Context, in *seqproxyapi.ComplexSearchRequest, opts ...grpc.CallOption) (*seqproxyapi.ComplexSearchResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ComplexSearch", varargs...)
	ret0, _ := ret[0].(*seqproxyapi.ComplexSearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ComplexSearch indicates an expected call of ComplexSearch.
func (mr *MockSeqProxyApiClientMockRecorder) ComplexSearch(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComplexSearch", reflect.TypeOf((*MockSeqProxyApiClient)(nil).ComplexSearch), varargs...)
}

// DeleteAsyncSearch mocks base method.
func (m *MockSeqProxyApiClient) DeleteAsyncSearch(ctx context.Context, in *seqproxyapi.DeleteAsyncSearchRequest, opts ...grpc.CallOption) (*seqproxyapi.DeleteAsyncSearchResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteAsyncSearch", varargs...)
	ret0, _ := ret[0].(*seqproxyapi.DeleteAsyncSearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAsyncSearch indicates an expected call of DeleteAsyncSearch.
func (mr *MockSeqProxyApiClientMockRecorder) DeleteAsyncSearch(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAsyncSearch", reflect.TypeOf((*MockSeqProxyApiClient)(nil).DeleteAsyncSearch), varargs...)
}

// Export mocks base method.
func (m *MockSeqProxyApiClient) Export(ctx context.Context, in *seqproxyapi.ExportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[seqproxyapi.ExportResponse], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Export", varargs...)
	ret0, _ := ret[0].(grpc.ServerStreamingClient[seqproxyapi.ExportResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Export indicates an expected call of Export.
func (mr *MockSeqProxyApiClientMockRecorder) Export(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Export", reflect.TypeOf((*MockSeqProxyApiClient)(nil).Export), varargs...)
}

// ExportAsyncSearch mocks base method.
func (m *MockSeqProxyApiClient) ExportAsyncSearch(ctx context.Context, in *seqproxyapi.ExportAsyncSearchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[seqproxyapi.ExportResponse], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExportAsyncSearch", varargs...)
	ret0, _ := ret[0].(grpc.ServerStreamingClient[seqproxyapi.ExportResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportAsyncSearch indicates an expected call of ExportAsyncSearch.
func (mr *MockSeqProxyApiClientMockRecorder) ExportAsyncSearch(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportAsyncSearch", reflect.TypeOf((*MockSeqProxyApiClient)(nil).ExportAsyncSearch), varargs...)
}

// Fetch mocks base method.
func (m *MockSeqProxyApiClient) Fetch(ctx context.Context, in *seqproxyapi.FetchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[seqproxyapi.Document], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Fetch", varargs...)
	ret0, _ := ret[0].(grpc.ServerStreamingClient[seqproxyapi.Document])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockSeqProxyApiClientMockRecorder) Fetch(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockSeqProxyApiClient)(nil).Fetch), varargs...)
}

// FetchAsyncSearchResult mocks base method.
func (m *MockSeqProxyApiClient) FetchAsyncSearchResult(ctx context.Context, in *seqproxyapi.FetchAsyncSearchResultRequest, opts ...grpc.CallOption) (*seqproxyapi.FetchAsyncSearchResultResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FetchAsyncSearchResult", varargs...)
	ret0, _ := ret[0].(*seqproxyapi.FetchAsyncSearchResultResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAsyncSearchResult indicates an expected call of FetchAsyncSearchResult.
func (mr *MockSeqProxyApiClientMockRecorder) FetchAsyncSearchResult(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAsyncSearchResult", reflect.TypeOf((*MockSeqProxyApiClient)(nil).FetchAsyncSearchResult), varargs...)
}

// GetAggregation mocks base method.
func (m *MockSeqProxyApiClient) GetAggregation(ctx context.Context, in *seqproxyapi.GetAggregationRequest, opts ...grpc.CallOption) (*seqproxyapi.GetAggregationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAggregation", varargs...)
	ret0, _ := ret[0].(*seqproxyapi.GetAggregationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAggregation indicates an expected call of GetAggregation.
func (mr *MockSeqProxyApiClientMockRecorder) GetAggregation(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAggregation", reflect.TypeOf((*MockSeqProxyApiClient)(nil).GetAggregation), varargs...)
}

// GetAsyncSearchesList mocks base method.
func (m *MockSeqProxyApiClient) GetAsyncSearchesList(ctx context.Context, in *seqproxyapi.GetAsyncSearchesListRequest, opts ...grpc.CallOption) (*seqproxyapi.GetAsyncSearchesListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAsyncSearchesList", varargs...)
	ret0, _ := ret[0].(*seqproxyapi.GetAsyncSearchesListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAsyncSearchesList indicates an expected call of GetAsyncSearchesList.
func (mr *MockSeqProxyApiClientMockRecorder) GetAsyncSearchesList(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAsyncSearchesList", reflect.TypeOf((*MockSeqProxyApiClient)(nil).GetAsyncSearchesList), varargs...)
}

// GetHistogram mocks base method.
func (m *MockSeqProxyApiClient) GetHistogram(ctx context.Context, in *seqproxyapi.GetHistogramRequest, opts ...grpc.CallOption) (*seqproxyapi.GetHistogramResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetHistogram", varargs...)
	ret0, _ := ret[0].(*seqproxyapi.GetHistogramResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistogram indicates an expected call of GetHistogram.
func (mr *MockSeqProxyApiClientMockRecorder) GetHistogram(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistogram", reflect.TypeOf((*MockSeqProxyApiClient)(nil).GetHistogram), varargs...)
}

// Mapping mocks base method.
func (m *MockSeqProxyApiClient) Mapping(ctx context.Context, in *seqproxyapi.MappingRequest, opts ...grpc.CallOption) (*seqproxyapi.MappingResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Mapping", varargs...)
	ret0, _ := ret[0].(*seqproxyapi.MappingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Mapping indicates an expected call of Mapping.
func (mr *MockSeqProxyApiClientMockRecorder) Mapping(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mapping", reflect.TypeOf((*MockSeqProxyApiClient)(nil).Mapping), varargs...)
}

// Search mocks base method.
func (m *MockSeqProxyApiClient) Search(ctx context.Context, in *seqproxyapi.SearchRequest, opts ...grpc.CallOption) (*seqproxyapi.SearchResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Search", varargs...)
	ret0, _ := ret[0].(*seqproxyapi.SearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockSeqProxyApiClientMockRecorder) Search(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSeqProxyApiClient)(nil).Search), varargs...)
}

// StartAsyncSearch mocks base method.
func (m *MockSeqProxyApiClient) StartAsyncSearch(ctx context.Context, in *seqproxyapi.StartAsyncSearchRequest, opts ...grpc.CallOption) (*seqproxyapi.StartAsyncSearchResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StartAsyncSearch", varargs...)
	ret0, _ := ret[0].(*seqproxyapi.StartAsyncSearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartAsyncSearch indicates an expected call of StartAsyncSearch.
func (mr *MockSeqProxyApiClientMockRecorder) StartAsyncSearch(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartAsyncSearch", reflect.TypeOf((*MockSeqProxyApiClient)(nil).StartAsyncSearch), varargs...)
}

// Status mocks base method.
func (m *MockSeqProxyApiClient) Status(ctx context.Context, in *seqproxyapi.StatusRequest, opts ...grpc.CallOption) (*seqproxyapi.StatusResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Status", varargs...)
	ret0, _ := ret[0].(*seqproxyapi.StatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockSeqProxyApiClientMockRecorder) Status(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockSeqProxyApiClient)(nil).Status), varargs...)
}

// MockSeqProxyApiServer is a mock of SeqProxyApiServer interface.
type MockSeqProxyApiServer struct {
	ctrl     *gomock.Controller
	recorder *MockSeqProxyApiServerMockRecorder
	isgomock struct{}
}

// MockSeqProxyApiServerMockRecorder is the mock recorder for MockSeqProxyApiServer.
type MockSeqProxyApiServerMockRecorder struct {
	mock *MockSeqProxyApiServer
}

// NewMockSeqProxyApiServer creates a new mock instance.
func NewMockSeqProxyApiServer(ctrl *gomock.Controller) *MockSeqProxyApiServer {
	mock := &MockSeqProxyApiServer{ctrl: ctrl}
	mock.recorder = &MockSeqProxyApiServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeqProxyApiServer) EXPECT() *MockSeqProxyApiServerMockRecorder {
	return m.recorder
}

// CancelAsyncSearch mocks base method.
func (m *MockSeqProxyApiServer) CancelAsyncSearch(arg0 context.Context, arg1 *seqproxyapi.CancelAsyncSearchRequest) (*seqproxyapi.CancelAsyncSearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelAsyncSearch", arg0, arg1)
	ret0, _ := ret[0].(*seqproxyapi.CancelAsyncSearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelAsyncSearch indicates an expected call of CancelAsyncSearch.
func (mr *MockSeqProxyApiServerMockRecorder) CancelAsyncSearch(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelAsyncSearch", reflect.TypeOf((*MockSeqProxyApiServer)(nil).CancelAsyncSearch), arg0, arg1)
}

// ComplexSearch mocks base method.
func (m *MockSeqProxyApiServer) ComplexSearch(arg0 context.Context, arg1 *seqproxyapi.ComplexSearchRequest) (*seqproxyapi.ComplexSearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComplexSearch", arg0, arg1)
	ret0, _ := ret[0].(*seqproxyapi.ComplexSearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ComplexSearch indicates an expected call of ComplexSearch.
func (mr *MockSeqProxyApiServerMockRecorder) ComplexSearch(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComplexSearch", reflect.TypeOf((*MockSeqProxyApiServer)(nil).ComplexSearch), arg0, arg1)
}

// DeleteAsyncSearch mocks base method.
func (m *MockSeqProxyApiServer) DeleteAsyncSearch(arg0 context.Context, arg1 *seqproxyapi.DeleteAsyncSearchRequest) (*seqproxyapi.DeleteAsyncSearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAsyncSearch", arg0, arg1)
	ret0, _ := ret[0].(*seqproxyapi.DeleteAsyncSearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAsyncSearch indicates an expected call of DeleteAsyncSearch.
func (mr *MockSeqProxyApiServerMockRecorder) DeleteAsyncSearch(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAsyncSearch", reflect.TypeOf((*MockSeqProxyApiServer)(nil).DeleteAsyncSearch), arg0, arg1)
}

// Export mocks base method.
func (m *MockSeqProxyApiServer) Export(arg0 *seqproxyapi.ExportRequest, arg1 grpc.ServerStreamingServer[seqproxyapi.ExportResponse]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Export", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Export indicates an expected call of Export.
func (mr *MockSeqProxyApiServerMockRecorder) Export(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Export", reflect.TypeOf((*MockSeqProxyApiServer)(nil).Export), arg0, arg1)
}

// ExportAsyncSearch mocks base method.
func (m *MockSeqProxyApiServer) ExportAsyncSearch(arg0 *seqproxyapi.ExportAsyncSearchRequest, arg1 grpc.ServerStreamingServer[seqproxyapi.ExportResponse]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportAsyncSearch", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExportAsyncSearch indicates an expected call of ExportAsyncSearch.
func (mr *MockSeqProxyApiServerMockRecorder) ExportAsyncSearch(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportAsyncSearch", reflect.TypeOf((*MockSeqProxyApiServer)(nil).ExportAsyncSearch), arg0, arg1)
}

// Fetch mocks base method.
func (m *MockSeqProxyApiServer) Fetch(arg0 *seqproxyapi.FetchRequest, arg1 grpc.ServerStreamingServer[seqproxyapi.Document]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Fetch indicates an expected call of Fetch.
func (mr *MockSeqProxyApiServerMockRecorder) Fetch(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockSeqProxyApiServer)(nil).Fetch), arg0, arg1)
}

// FetchAsyncSearchResult mocks base method.
func (m *MockSeqProxyApiServer) FetchAsyncSearchResult(arg0 context.Context, arg1 *seqproxyapi.FetchAsyncSearchResultRequest) (*seqproxyapi.FetchAsyncSearchResultResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAsyncSearchResult", arg0, arg1)
	ret0, _ := ret[0].(*seqproxyapi.FetchAsyncSearchResultResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAsyncSearchResult indicates an expected call of FetchAsyncSearchResult.
func (mr *MockSeqProxyApiServerMockRecorder) FetchAsyncSearchResult(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAsyncSearchResult", reflect.TypeOf((*MockSeqProxyApiServer)(nil).FetchAsyncSearchResult), arg0, arg1)
}

// GetAggregation mocks base method.
func (m *MockSeqProxyApiServer) GetAggregation(arg0 context.Context, arg1 *seqproxyapi.GetAggregationRequest) (*seqproxyapi.GetAggregationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAggregation", arg0, arg1)
	ret0, _ := ret[0].(*seqproxyapi.GetAggregationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAggregation indicates an expected call of GetAggregation.
func (mr *MockSeqProxyApiServerMockRecorder) GetAggregation(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAggregation", reflect.TypeOf((*MockSeqProxyApiServer)(nil).GetAggregation), arg0, arg1)
}

// GetAsyncSearchesList mocks base method.
func (m *MockSeqProxyApiServer) GetAsyncSearchesList(arg0 context.Context, arg1 *seqproxyapi.GetAsyncSearchesListRequest) (*seqproxyapi.GetAsyncSearchesListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAsyncSearchesList", arg0, arg1)
	ret0, _ := ret[0].(*seqproxyapi.GetAsyncSearchesListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAsyncSearchesList indicates an expected call of GetAsyncSearchesList.
func (mr *MockSeqProxyApiServerMockRecorder) GetAsyncSearchesList(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAsyncSearchesList", reflect.TypeOf((*MockSeqProxyApiServer)(nil).GetAsyncSearchesList), arg0, arg1)
}

// GetHistogram mocks base method.
func (m *MockSeqProxyApiServer) GetHistogram(arg0 context.Context, arg1 *seqproxyapi.GetHistogramRequest) (*seqproxyapi.GetHistogramResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistogram", arg0, arg1)
	ret0, _ := ret[0].(*seqproxyapi.GetHistogramResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistogram indicates an expected call of GetHistogram.
func (mr *MockSeqProxyApiServerMockRecorder) GetHistogram(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistogram", reflect.TypeOf((*MockSeqProxyApiServer)(nil).GetHistogram), arg0, arg1)
}

// Mapping mocks base method.
func (m *MockSeqProxyApiServer) Mapping(arg0 context.Context, arg1 *seqproxyapi.MappingRequest) (*seqproxyapi.MappingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mapping", arg0, arg1)
	ret0, _ := ret[0].(*seqproxyapi.MappingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Mapping indicates an expected call of Mapping.
func (mr *MockSeqProxyApiServerMockRecorder) Mapping(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mapping", reflect.TypeOf((*MockSeqProxyApiServer)(nil).Mapping), arg0, arg1)
}

// Search mocks base method.
func (m *MockSeqProxyApiServer) Search(arg0 context.Context, arg1 *seqproxyapi.SearchRequest) (*seqproxyapi.SearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", arg0, arg1)
	ret0, _ := ret[0].(*seqproxyapi.SearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockSeqProxyApiServerMockRecorder) Search(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSeqProxyApiServer)(nil).Search), arg0, arg1)
}

// StartAsyncSearch mocks base method.
func (m *MockSeqProxyApiServer) StartAsyncSearch(arg0 context.Context, arg1 *seqproxyapi.StartAsyncSearchRequest) (*seqproxyapi.StartAsyncSearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartAsyncSearch", arg0, arg1)
	ret0, _ := ret[0].(*seqproxyapi.StartAsyncSearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartAsyncSearch indicates an expected call of StartAsyncSearch.
func (mr *MockSeqProxyApiServerMockRecorder) StartAsyncSearch(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartAsyncSearch", reflect.TypeOf((*MockSeqProxyApiServer)(nil).StartAsyncSearch), arg0, arg1)
}

// Status mocks base method.
func (m *MockSeqProxyApiServer) Status(arg0 context.Context, arg1 *seqproxyapi.StatusRequest) (*seqproxyapi.StatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", arg0, arg1)
	ret0, _ := ret[0].(*seqproxyapi.StatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockSeqProxyApiServerMockRecorder) Status(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockSeqProxyApiServer)(nil).Status), arg0, arg1)
}

// MockUnsafeSeqProxyApiServer is a mock of UnsafeSeqProxyApiServer interface.
type MockUnsafeSeqProxyApiServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeSeqProxyApiServerMockRecorder
	isgomock struct{}
}

// MockUnsafeSeqProxyApiServerMockRecorder is the mock recorder for MockUnsafeSeqProxyApiServer.
type MockUnsafeSeqProxyApiServerMockRecorder struct {
	mock *MockUnsafeSeqProxyApiServer
}

// NewMockUnsafeSeqProxyApiServer creates a new mock instance.
func NewMockUnsafeSeqProxyApiServer(ctrl *gomock.Controller) *MockUnsafeSeqProxyApiServer {
	mock := &MockUnsafeSeqProxyApiServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeSeqProxyApiServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeSeqProxyApiServer) EXPECT() *MockUnsafeSeqProxyApiServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedSeqProxyApiServer mocks base method.
func (m *MockUnsafeSeqProxyApiServer) mustEmbedUnimplementedSeqProxyApiServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedSeqProxyApiServer")
}

// mustEmbedUnimplementedSeqProxyApiServer indicates an expected call of mustEmbedUnimplementedSeqProxyApiServer.
func (mr *MockUnsafeSeqProxyApiServerMockRecorder) mustEmbedUnimplementedSeqProxyApiServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedSeqProxyApiServer", reflect.TypeOf((*MockUnsafeSeqProxyApiServer)(nil).mustEmbedUnimplementedSeqProxyApiServer))
}

// MockSeqProxyApi_FetchServer is a mock of SeqProxyApi_FetchServer interface.
type MockSeqProxyApi_FetchServer[Res any] struct {
	ctrl     *gomock.Controller
	recorder *MockSeqProxyApi_FetchServerMockRecorder[Res]
	isgomock struct{}
}

// MockSeqProxyApi_FetchServerMockRecorder is the mock recorder for MockSeqProxyApi_FetchServer.
type MockSeqProxyApi_FetchServerMockRecorder[Res any] struct {
	mock *MockSeqProxyApi_FetchServer[Res]
}

// NewMockSeqProxyApi_FetchServer creates a new mock instance.
func NewMockSeqProxyApi_FetchServer[Res any](ctrl *gomock.Controller) *MockSeqProxyApi_FetchServer[Res] {
	mock := &MockSeqProxyApi_FetchServer[Res]{ctrl: ctrl}
	mock.recorder = &MockSeqProxyApi_FetchServerMockRecorder[Res]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeqProxyApi_FetchServer[Res]) EXPECT() *MockSeqProxyApi_FetchServerMockRecorder[Res] {
	return m.recorder
}

// Context mocks base method.
func (m *MockSeqProxyApi_FetchServer[Res]) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockSeqProxyApi_FetchServerMockRecorder[Res]) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockSeqProxyApi_FetchServer[Res])(nil).Context))
}

// RecvMsg mocks base method.
func (m_2 *MockSeqProxyApi_FetchServer[Res]) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockSeqProxyApi_FetchServerMockRecorder[Res]) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockSeqProxyApi_FetchServer[Res])(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockSeqProxyApi_FetchServer[Res]) Send(arg0 *seqproxyapi.Document) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockSeqProxyApi_FetchServerMockRecorder[Res]) Send(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockSeqProxyApi_FetchServer[Res])(nil).Send), arg0)
}

// SendHeader mocks base method.
func (m *MockSeqProxyApi_FetchServer[Res]) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockSeqProxyApi_FetchServerMockRecorder[Res]) SendHeader(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockSeqProxyApi_FetchServer[Res])(nil).SendHeader), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockSeqProxyApi_FetchServer[Res]) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockSeqProxyApi_FetchServerMockRecorder[Res]) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockSeqProxyApi_FetchServer[Res])(nil).SendMsg), m)
}

// SetHeader mocks base method.
func (m *MockSeqProxyApi_FetchServer[Res]) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockSeqProxyApi_FetchServerMockRecorder[Res]) SetHeader(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockSeqProxyApi_FetchServer[Res])(nil).SetHeader), arg0)
}

// SetTrailer mocks base method.
func (m *MockSeqProxyApi_FetchServer[Res]) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockSeqProxyApi_FetchServerMockRecorder[Res]) SetTrailer(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockSeqProxyApi_FetchServer[Res])(nil).SetTrailer), arg0)
}

// MockSeqProxyApi_ExportServer is a mock of SeqProxyApi_ExportServer interface.
type MockSeqProxyApi_ExportServer[Res any] struct {
	ctrl     *gomock.Controller
	recorder *MockSeqProxyApi_ExportServerMockRecorder[Res]
	isgomock struct{}
}

// MockSeqProxyApi_ExportServerMockRecorder is the mock recorder for MockSeqProxyApi_ExportServer.
type MockSeqProxyApi_ExportServerMockRecorder[Res any] struct {
	mock *MockSeqProxyApi_ExportServer[Res]
}

// NewMockSeqProxyApi_ExportServer creates a new mock instance.
func NewMockSeqProxyApi_ExportServer[Res any](ctrl *gomock.Controller) *MockSeqProxyApi_ExportServer[Res] {
	mock := &MockSeqProxyApi_ExportServer[Res]{ctrl: ctrl}
	mock.recorder = &MockSeqProxyApi_ExportServerMockRecorder[Res]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeqProxyApi_ExportServer[Res]) EXPECT() *MockSeqProxyApi_ExportServerMockRecorder[Res] {
	return m.recorder
}

// Context mocks base method.
func (m *MockSeqProxyApi_ExportServer[Res]) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockSeqProxyApi_ExportServerMockRecorder[Res]) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockSeqProxyApi_ExportServer[Res])(nil).Context))
}

// RecvMsg mocks base method.
func (m_2 *MockSeqProxyApi_ExportServer[Res]) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockSeqProxyApi_ExportServerMockRecorder[Res]) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockSeqProxyApi_ExportServer[Res])(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockSeqProxyApi_ExportServer[Res]) Send(arg0 *seqproxyapi.ExportResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockSeqProxyApi_ExportServerMockRecorder[Res]) Send(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockSeqProxyApi_ExportServer[Res])(nil).Send), arg0)
}

// SendHeader mocks base method.
func (m *MockSeqProxyApi_ExportServer[Res]) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockSeqProxyApi_ExportServerMockRecorder[Res]) SendHeader(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockSeqProxyApi_ExportServer[Res])(nil).SendHeader), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockSeqProxyApi_ExportServer[Res]) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockSeqProxyApi_ExportServerMockRecorder[Res]) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockSeqProxyApi_ExportServer[Res])(nil).SendMsg), m)
}

// SetHeader mocks base method.
func (m *MockSeqProxyApi_ExportServer[Res]) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockSeqProxyApi_ExportServerMockRecorder[Res]) SetHeader(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockSeqProxyApi_ExportServer[Res])(nil).SetHeader), arg0)
}

// SetTrailer mocks base method.
func (m *MockSeqProxyApi_ExportServer[Res]) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockSeqProxyApi_ExportServerMockRecorder[Res]) SetTrailer(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockSeqProxyApi_ExportServer[Res])(nil).SetTrailer), arg0)
}

// MockSeqProxyApi_ExportAsyncSearchServer is a mock of SeqProxyApi_ExportAsyncSearchServer interface.
type MockSeqProxyApi_ExportAsyncSearchServer[Res any] struct {
	ctrl     *gomock.Controller
	recorder *MockSeqProxyApi_ExportAsyncSearchServerMockRecorder[Res]
	isgomock struct{}
}

// MockSeqProxyApi_ExportAsyncSearchServerMockRecorder is the mock recorder for MockSeqProxyApi_ExportAsyncSearchServer.
type MockSeqProxyApi_ExportAsyncSearchServerMockRecorder[Res any] struct {
	mock *MockSeqProxyApi_ExportAsyncSearchServer[Res]
}

// NewMockSeqProxyApi_ExportAsyncSearchServer creates a new mock instance.
func NewMockSeqProxyApi_ExportAsyncSearchServer[Res any](ctrl *gomock.Controller) *MockSeqProxyApi_ExportAsyncSearchServer[Res] {
	mock := &MockSeqProxyApi_ExportAsyncSearchServer[Res]{ctrl: ctrl}
	mock.recorder = &MockSeqProxyApi_ExportAsyncSearchServerMockRecorder[Res]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeqProxyApi_ExportAsyncSearchServer[Res]) EXPECT() *MockSeqProxyApi_ExportAsyncSearchServerMockRecorder[Res] {
	return m.recorder
}

// Context mocks base method.
func (m *MockSeqProxyApi_ExportAsyncSearchServer[Res]) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockSeqProxyApi_ExportAsyncSearchServerMockRecorder[Res]) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockSeqProxyApi_ExportAsyncSearchServer[Res])(nil).Context))
}

// RecvMsg mocks base method.
func (m_2 *MockSeqProxyApi_ExportAsyncSearchServer[Res]) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockSeqProxyApi_ExportAsyncSearchServerMockRecorder[Res]) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockSeqProxyApi_ExportAsyncSearchServer[Res])(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockSeqProxyApi_ExportAsyncSearchServer[Res]) Send(arg0 *seqproxyapi.ExportResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockSeqProxyApi_ExportAsyncSearchServerMockRecorder[Res]) Send(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockSeqProxyApi_ExportAsyncSearchServer[Res])(nil).Send), arg0)
}

// SendHeader mocks base method.
func (m *MockSeqProxyApi_ExportAsyncSearchServer[Res]) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockSeqProxyApi_ExportAsyncSearchServerMockRecorder[Res]) SendHeader(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockSeqProxyApi_ExportAsyncSearchServer[Res])(nil).SendHeader), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockSeqProxyApi_ExportAsyncSearchServer[Res]) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockSeqProxyApi_ExportAsyncSearchServerMockRecorder[Res]) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockSeqProxyApi_ExportAsyncSearchServer[Res])(nil).SendMsg), m)
}

// SetHeader mocks base method.
func (m *MockSeqProxyApi_ExportAsyncSearchServer[Res]) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockSeqProxyApi_ExportAsyncSearchServerMockRecorder[Res]) SetHeader(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockSeqProxyApi_ExportAsyncSearchServer[Res])(nil).SetHeader), arg0)
}

// SetTrailer mocks base method.
func (m *MockSeqProxyApi_ExportAsyncSearchServer[Res]) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockSeqProxyApi_ExportAsyncSearchServerMockRecorder[Res]) SetTrailer(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockSeqProxyApi_ExportAsyncSearchServer[Res])(nil).SetTrailer), arg0)
}

// MockSeqProxyApi_FetchClient is a mock of SeqProxyApi_FetchClient interface.
type MockSeqProxyApi_FetchClient[Res any] struct {
	ctrl     *gomock.Controller
	recorder *MockSeqProxyApi_FetchClientMockRecorder[Res]
	isgomock struct{}
}

// MockSeqProxyApi_FetchClientMockRecorder is the mock recorder for MockSeqProxyApi_FetchClient.
type MockSeqProxyApi_FetchClientMockRecorder[Res any] struct {
	mock *MockSeqProxyApi_FetchClient[Res]
}

// NewMockSeqProxyApi_FetchClient creates a new mock instance.
func NewMockSeqProxyApi_FetchClient[Res any](ctrl *gomock.Controller) *MockSeqProxyApi_FetchClient[Res] {
	mock := &MockSeqProxyApi_FetchClient[Res]{ctrl: ctrl}
	mock.recorder = &MockSeqProxyApi_FetchClientMockRecorder[Res]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeqProxyApi_FetchClient[Res]) EXPECT() *MockSeqProxyApi_FetchClientMockRecorder[Res] {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockSeqProxyApi_FetchClient[Res]) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockSeqProxyApi_FetchClientMockRecorder[Res]) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockSeqProxyApi_FetchClient[Res])(nil).CloseSend))
}

// Context mocks base method.
func (m *MockSeqProxyApi_FetchClient[Res]) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockSeqProxyApi_FetchClientMockRecorder[Res]) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockSeqProxyApi_FetchClient[Res])(nil).Context))
}

// Header mocks base method.
func (m *MockSeqProxyApi_FetchClient[Res]) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockSeqProxyApi_FetchClientMockRecorder[Res]) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockSeqProxyApi_FetchClient[Res])(nil).Header))
}

// Recv mocks base method.
func (m *MockSeqProxyApi_FetchClient[Res]) Recv() (*seqproxyapi.Document, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*seqproxyapi.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockSeqProxyApi_FetchClientMockRecorder[Res]) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockSeqProxyApi_FetchClient[Res])(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockSeqProxyApi_FetchClient[Res]) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockSeqProxyApi_FetchClientMockRecorder[Res]) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockSeqProxyApi_FetchClient[Res])(nil).RecvMsg), m)
}

// SendMsg mocks base method.
func (m_2 *MockSeqProxyApi_FetchClient[Res]) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockSeqProxyApi_FetchClientMockRecorder[Res]) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockSeqProxyApi_FetchClient[Res])(nil).SendMsg), m)
}

// Trailer mocks base method.
func (m *MockSeqProxyApi_FetchClient[Res]) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockSeqProxyApi_FetchClientMockRecorder[Res]) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockSeqProxyApi_FetchClient[Res])(nil).Trailer))
}

// MockSeqProxyApi_ExportClient is a mock of SeqProxyApi_ExportClient interface.
type MockSeqProxyApi_ExportClient[Res any] struct {
	ctrl     *gomock.Controller
	recorder *MockSeqProxyApi_ExportClientMockRecorder[Res]
	isgomock struct{}
}

// MockSeqProxyApi_ExportClientMockRecorder is the mock recorder for MockSeqProxyApi_ExportClient.
type MockSeqProxyApi_ExportClientMockRecorder[Res any] struct {
	mock *MockSeqProxyApi_ExportClient[Res]
}

// NewMockSeqProxyApi_ExportClient creates a new mock instance.
func NewMockSeqProxyApi_ExportClient[Res any](ctrl *gomock.Controller) *MockSeqProxyApi_ExportClient[Res] {
	mock := &MockSeqProxyApi_ExportClient[Res]{ctrl: ctrl}
	mock.recorder = &MockSeqProxyApi_ExportClientMockRecorder[Res]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeqProxyApi_ExportClient[Res]) EXPECT() *MockSeqProxyApi_ExportClientMockRecorder[Res] {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockSeqProxyApi_ExportClient[Res]) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockSeqProxyApi_ExportClientMockRecorder[Res]) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockSeqProxyApi_ExportClient[Res])(nil).CloseSend))
}

// Context mocks base method.
func (m *MockSeqProxyApi_ExportClient[Res]) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockSeqProxyApi_ExportClientMockRecorder[Res]) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockSeqProxyApi_ExportClient[Res])(nil).Context))
}

// Header mocks base method.
func (m *MockSeqProxyApi_ExportClient[Res]) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockSeqProxyApi_ExportClientMockRecorder[Res]) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockSeqProxyApi_ExportClient[Res])(nil).Header))
}

// Recv mocks base method.
func (m *MockSeqProxyApi_ExportClient[Res]) Recv() (*seqproxyapi.ExportResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*seqproxyapi.ExportResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockSeqProxyApi_ExportClientMockRecorder[Res]) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockSeqProxyApi_ExportClient[Res])(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockSeqProxyApi_ExportClient[Res]) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockSeqProxyApi_ExportClientMockRecorder[Res]) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockSeqProxyApi_ExportClient[Res])(nil).RecvMsg), m)
}

// SendMsg mocks base method.
func (m_2 *MockSeqProxyApi_ExportClient[Res]) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockSeqProxyApi_ExportClientMockRecorder[Res]) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockSeqProxyApi_ExportClient[Res])(nil).SendMsg), m)
}

// Trailer mocks base method.
func (m *MockSeqProxyApi_ExportClient[Res]) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockSeqProxyApi_ExportClientMockRecorder[Res]) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockSeqProxyApi_ExportClient[Res])(nil).Trailer))
}

// MockSeqProxyApi_ExportAsyncSearchClient is a mock of SeqProxyApi_ExportAsyncSearchClient interface.
type MockSeqProxyApi_ExportAsyncSearchClient[Res any] struct {
	ctrl     *gomock.Controller
	recorder *MockSeqProxyApi_ExportAsyncSearchClientMockRecorder[Res]
	isgomock struct{}
}

// MockSeqProxyApi_ExportAsyncSearchClientMockRecorder is the mock recorder for MockSeqProxyApi_ExportAsyncSearchClient.
type MockSeqProxyApi_ExportAsyncSearchClientMockRecorder[Res any] struct {
	mock *MockSeqProxyApi_ExportAsyncSearchClient[Res]
}

// NewMockSeqProxyApi_ExportAsyncSearchClient creates a new mock instance.
func NewMockSeqProxyApi_ExportAsyncSearchClient[Res any](ctrl *gomock.Controller) *MockSeqProxyApi_ExportAsyncSearchClient[Res] {
	mock := &MockSeqProxyApi_ExportAsyncSearchClient[Res]{ctrl: ctrl}
	mock.recorder = &MockSeqProxyApi_ExportAsyncSearchClientMockRecorder[Res]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeqProxyApi_ExportAsyncSearchClient[Res]) EXPECT() *MockSeqProxyApi_ExportAsyncSearchClientMockRecorder[Res] {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockSeqProxyApi_ExportAsyncSearchClient[Res]) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockSeqProxyApi_ExportAsyncSearchClientMockRecorder[Res]) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockSeqProxyApi_ExportAsyncSearchClient[Res])(nil).CloseSend))
}

// Context mocks base method.
func (m *MockSeqProxyApi_ExportAsyncSearchClient[Res]) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockSeqProxyApi_ExportAsyncSearchClientMockRecorder[Res]) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockSeqProxyApi_ExportAsyncSearchClient[Res])(nil).Context))
}

// Header mocks base method.
func (m *MockSeqProxyApi_ExportAsyncSearchClient[Res]) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockSeqProxyApi_ExportAsyncSearchClientMockRecorder[Res]) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockSeqProxyApi_ExportAsyncSearchClient[Res])(nil).Header))
}

// Recv mocks base method.
func (m *MockSeqProxyApi_ExportAsyncSearchClient[Res]) Recv() (*seqproxyapi.ExportResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*seqproxyapi.ExportResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockSeqProxyApi_ExportAsyncSearchClientMockRecorder[Res]) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockSeqProxyApi_ExportAsyncSearchClient[Res])(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockSeqProxyApi_ExportAsyncSearchClient[Res]) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockSeqProxyApi_ExportAsyncSearchClientMockRecorder[Res]) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockSeqProxyApi_ExportAsyncSearchClient[Res])(nil).RecvMsg), m)
}

// SendMsg mocks base method.
func (m_2 *MockSeqProxyApi_ExportAsyncSearchClient[Res]) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockSeqProxyApi_ExportAsyncSearchClientMockRecorder[Res]) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockSeqProxyApi_ExportAsyncSearchClient[Res])(nil).SendMsg), m)
}

// Trailer mocks base method.
func (m *MockSeqProxyApi_ExportAsyncSearchClient[Res]) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockSeqProxyApi_ExportAsyncSearchClientMockRecorder[Res]) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockSeqProxyApi_ExportAsyncSearchClient[Res])(nil).Trailer))
}
