// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ozontech/seq-ui/internal/pkg/service/massexport (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=internal/pkg/service/massexport/mock/service.go github.com/ozontech/seq-ui/internal/pkg/service/massexport Service
//

// Package mock_massexport is a generated GoMock package.
package mock_massexport

import (
	context "context"
	reflect "reflect"

	types "github.com/ozontech/seq-ui/internal/app/types"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CancelExport mocks base method.
func (m *MockService) CancelExport(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelExport", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelExport indicates an expected call of CancelExport.
func (mr *MockServiceMockRecorder) CancelExport(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelExport", reflect.TypeOf((*MockService)(nil).CancelExport), ctx, sessionID)
}

// CheckExport mocks base method.
func (m *MockService) CheckExport(ctx context.Context, sessionID string) (types.ExportInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckExport", ctx, sessionID)
	ret0, _ := ret[0].(types.ExportInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckExport indicates an expected call of CheckExport.
func (mr *MockServiceMockRecorder) CheckExport(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckExport", reflect.TypeOf((*MockService)(nil).CheckExport), ctx, sessionID)
}

// GetAll mocks base method.
func (m *MockService) GetAll(ctx context.Context) ([]types.ExportInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]types.ExportInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockServiceMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockService)(nil).GetAll), ctx)
}

// RestoreExport mocks base method.
func (m *MockService) RestoreExport(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreExport", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestoreExport indicates an expected call of RestoreExport.
func (mr *MockServiceMockRecorder) RestoreExport(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreExport", reflect.TypeOf((*MockService)(nil).RestoreExport), ctx, sessionID)
}

// StartExport mocks base method.
func (m *MockService) StartExport(ctx context.Context, req types.StartExportRequest) (types.StartExportResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartExport", ctx, req)
	ret0, _ := ret[0].(types.StartExportResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartExport indicates an expected call of StartExport.
func (mr *MockServiceMockRecorder) StartExport(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartExport", reflect.TypeOf((*MockService)(nil).StartExport), ctx, req)
}
