// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ozontech/seq-ui/internal/pkg/repository_ch (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=internal/pkg/repository_ch/mock/repository_ch.go -package=mock_repositorych github.com/ozontech/seq-ui/internal/pkg/repository_ch Repository
//

// Package mock_repositorych is a generated GoMock package.
package mock_repositorych

import (
	context "context"
	reflect "reflect"

	types "github.com/ozontech/seq-ui/internal/app/types"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// DiffByReleases mocks base method.
func (m *MockRepository) DiffByReleases(arg0 context.Context, arg1 types.DiffByReleasesRequest) ([]types.DiffGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiffByReleases", arg0, arg1)
	ret0, _ := ret[0].([]types.DiffGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DiffByReleases indicates an expected call of DiffByReleases.
func (mr *MockRepositoryMockRecorder) DiffByReleases(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiffByReleases", reflect.TypeOf((*MockRepository)(nil).DiffByReleases), arg0, arg1)
}

// DiffByReleasesTotal mocks base method.
func (m *MockRepository) DiffByReleasesTotal(arg0 context.Context, arg1 types.DiffByReleasesRequest) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiffByReleasesTotal", arg0, arg1)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DiffByReleasesTotal indicates an expected call of DiffByReleasesTotal.
func (mr *MockRepositoryMockRecorder) DiffByReleasesTotal(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiffByReleasesTotal", reflect.TypeOf((*MockRepository)(nil).DiffByReleasesTotal), arg0, arg1)
}

// GetErrorCounts mocks base method.
func (m *MockRepository) GetErrorCounts(arg0 context.Context, arg1 types.GetErrorGroupDetailsRequest) (types.ErrorGroupCounts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetErrorCounts", arg0, arg1)
	ret0, _ := ret[0].(types.ErrorGroupCounts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetErrorCounts indicates an expected call of GetErrorCounts.
func (mr *MockRepositoryMockRecorder) GetErrorCounts(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetErrorCounts", reflect.TypeOf((*MockRepository)(nil).GetErrorCounts), arg0, arg1)
}

// GetErrorDetails mocks base method.
func (m *MockRepository) GetErrorDetails(arg0 context.Context, arg1 types.GetErrorGroupDetailsRequest) (types.ErrorGroupDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetErrorDetails", arg0, arg1)
	ret0, _ := ret[0].(types.ErrorGroupDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetErrorDetails indicates an expected call of GetErrorDetails.
func (mr *MockRepositoryMockRecorder) GetErrorDetails(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetErrorDetails", reflect.TypeOf((*MockRepository)(nil).GetErrorDetails), arg0, arg1)
}

// GetErrorGroups mocks base method.
func (m *MockRepository) GetErrorGroups(arg0 context.Context, arg1 types.GetErrorGroupsRequest) ([]types.ErrorGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetErrorGroups", arg0, arg1)
	ret0, _ := ret[0].([]types.ErrorGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetErrorGroups indicates an expected call of GetErrorGroups.
func (mr *MockRepositoryMockRecorder) GetErrorGroups(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetErrorGroups", reflect.TypeOf((*MockRepository)(nil).GetErrorGroups), arg0, arg1)
}

// GetErrorGroupsTotal mocks base method.
func (m *MockRepository) GetErrorGroupsTotal(arg0 context.Context, arg1 types.GetErrorGroupsRequest) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetErrorGroupsTotal", arg0, arg1)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetErrorGroupsTotal indicates an expected call of GetErrorGroupsTotal.
func (mr *MockRepositoryMockRecorder) GetErrorGroupsTotal(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetErrorGroupsTotal", reflect.TypeOf((*MockRepository)(nil).GetErrorGroupsTotal), arg0, arg1)
}

// GetErrorHist mocks base method.
func (m *MockRepository) GetErrorHist(arg0 context.Context, arg1 types.GetErrorHistRequest) ([]types.ErrorHistBucket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetErrorHist", arg0, arg1)
	ret0, _ := ret[0].([]types.ErrorHistBucket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetErrorHist indicates an expected call of GetErrorHist.
func (mr *MockRepositoryMockRecorder) GetErrorHist(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetErrorHist", reflect.TypeOf((*MockRepository)(nil).GetErrorHist), arg0, arg1)
}

// GetNewErrorGroups mocks base method.
func (m *MockRepository) GetNewErrorGroups(arg0 context.Context, arg1 types.GetErrorGroupsRequest) ([]types.ErrorGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNewErrorGroups", arg0, arg1)
	ret0, _ := ret[0].([]types.ErrorGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNewErrorGroups indicates an expected call of GetNewErrorGroups.
func (mr *MockRepositoryMockRecorder) GetNewErrorGroups(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNewErrorGroups", reflect.TypeOf((*MockRepository)(nil).GetNewErrorGroups), arg0, arg1)
}

// GetNewErrorGroupsTotal mocks base method.
func (m *MockRepository) GetNewErrorGroupsTotal(arg0 context.Context, arg1 types.GetErrorGroupsRequest) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNewErrorGroupsTotal", arg0, arg1)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNewErrorGroupsTotal indicates an expected call of GetNewErrorGroupsTotal.
func (mr *MockRepositoryMockRecorder) GetNewErrorGroupsTotal(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNewErrorGroupsTotal", reflect.TypeOf((*MockRepository)(nil).GetNewErrorGroupsTotal), arg0, arg1)
}

// GetReleases mocks base method.
func (m *MockRepository) GetReleases(arg0 context.Context, arg1 types.GetReleasesRequest) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReleases", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReleases indicates an expected call of GetReleases.
func (mr *MockRepositoryMockRecorder) GetReleases(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReleases", reflect.TypeOf((*MockRepository)(nil).GetReleases), arg0, arg1)
}

// GetServices mocks base method.
func (m *MockRepository) GetServices(arg0 context.Context, arg1 types.GetServicesRequest) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServices", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServices indicates an expected call of GetServices.
func (mr *MockRepositoryMockRecorder) GetServices(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServices", reflect.TypeOf((*MockRepository)(nil).GetServices), arg0, arg1)
}

// GetTopErrorGroups mocks base method.
func (m *MockRepository) GetTopErrorGroups(arg0 context.Context, arg1 types.GetTopErrorGroupsRequest) ([]types.TopErrorGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopErrorGroups", arg0, arg1)
	ret0, _ := ret[0].([]types.TopErrorGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopErrorGroups indicates an expected call of GetTopErrorGroups.
func (mr *MockRepositoryMockRecorder) GetTopErrorGroups(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopErrorGroups", reflect.TypeOf((*MockRepository)(nil).GetTopErrorGroups), arg0, arg1)
}

// GetTopErrorGroupsTotal mocks base method.
func (m *MockRepository) GetTopErrorGroupsTotal(arg0 context.Context, arg1 types.GetTopErrorGroupsRequest) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopErrorGroupsTotal", arg0, arg1)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopErrorGroupsTotal indicates an expected call of GetTopErrorGroupsTotal.
func (mr *MockRepositoryMockRecorder) GetTopErrorGroupsTotal(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopErrorGroupsTotal", reflect.TypeOf((*MockRepository)(nil).GetTopErrorGroupsTotal), arg0, arg1)
}
